import { organizationToday, parseQuoteValidity } from "@/lib/ai/validity";
import { isPaymentOnlyDescription, normalizePaymentTerms, parsePaymentDetails } from "@/lib/domain/payment-terms";
import type { z } from "zod";
import { entitySchema } from "./schemas";
type Entity=z.infer<typeof entitySchema>;
const words:Record<string,number>={um:1,uma:1,dois:2,duas:2,tres:3,quatro:4,cinco:5,seis:6,sete:7,oito:8,nove:9,dez:10,vinte:20};
const entity=(value:string|number,raw:string,confidence=.95,requiresConfirmation=false):Entity=>({value,source:"user_message",raw,confidence,normalized:String(value),requiresConfirmation});
export function extractEntities(text:string,input:{now?:Date;timeZone?:string;today?:string}={}){
 const out:Record<string,Entity>={},plain=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),today=input.today??organizationToday(input.now,input.timeZone),purchaseOrder=/\bpedido\s+de\s+compra\b/.test(plain);
 const price=/r\$\s*([\d.]+(?:,\d{1,2})?)/i.exec(text)??/\b([\d.]+(?:,\d{1,2})?)\s*reais?\b/i.exec(text)??/\ba\s+([\d.]+(?:,\d{1,2})?)\s+cada\b/i.exec(text)??/(?:valor(?:\s+(?:total|unitario|de cada))?\s+(?:de\s+)?)([\d.]+(?:,\d{1,2})?)/i.exec(text);if(price){const value=Number(price[1].replace(/\./g,"").replace(",","."));if(Number.isFinite(value))out.price=entity(value,price[0]);}
 const leadingItemSegment=/(?:orçamento|orcamento|pedido\s+de\s+compra)\s+de\s+(.+?)(?=\s+para\s+(?:(?:a|o)\s+)?(?:empresa|cliente|fornecedor)\b|\s+(?:por|a)\s+(?:r\$\s*)?[\d.]|\s+pagamento\b|$)/iu.exec(text)?.[1];
 const counterpartItemSegment=/(?:empresa|cliente|fornecedor)\s+[\p{L}0-9 .&-]+?\s+de\s+(.+?)(?=\s+(?:por|a)\s+(?:r\$\s*)?[\d.]|\s+pagamento\b|$)/iu.exec(text)?.[1];
 const explicitItemSegment=/(\d+|um|uma|dois|duas|tres|quatro|cinco|seis|sete|oito|nove|dez|vinte)\s+([\p{L}][\p{L}\s-]*?)\s+(?:a|por)\s+(?:r\$\s*)?[\d.,]+(?:\s*reais?)?\s*cada\b/iu.exec(text);
 const itemSegment=leadingItemSegment??counterpartItemSegment??(explicitItemSegment?`${explicitItemSegment[1]} ${explicitItemSegment[2]}`:undefined);
 const quantitySource=(itemSegment??plain).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const quantity=/(\d+|um|uma|dois|duas|tres|quatro|cinco|seis|sete|oito|nove|dez|vinte)\s+([\p{L}][\p{L}-]{1,40})/iu.exec(quantitySource);if(quantity){const amount=Number(quantity[1])||words[quantity[1]],rawDescription=itemSegment?.trim()??quantity[0],descriptionRaw=rawDescription.replace(new RegExp(`^${quantity[1]}\\s+`,"i"),"").trim(),description=descriptionRaw.charAt(0).toLocaleUpperCase("pt-BR")+descriptionRaw.slice(1);out.quantity=entity(amount,quantity[0]);out.service=entity(description,rawDescription,.97);}
 const labelledCompany=/(?:para\s+(?:a|o)\s+)?(empresa|cliente|fornecedor)\s+([\p{L}0-9][\p{L}0-9 .&-]{1,60}?)(?=\s+de\s+|\s+(?:no\s+)?valor\s+de\b|,|\s+por\s+|$)/iu.exec(text);
 const contextualCompany=/(?:orçamento|orcamento|cotação|cotacao|pedido(?:\s+de\s+compra)?)\s+para\s+(?:(?:a|o)\s+)?([\p{L}0-9][\p{L}0-9 .&-]{1,60}?)(?=\s+de\s+(?=(?:\d+|um|uma|dois|duas|tr[eê]s|quatro|cinco|seis|sete|oito|nove|dez|vinte)\b)|,|$)/iu.exec(text);
 if(labelledCompany)out.customer=entity(`${labelledCompany[1].toLocaleLowerCase("pt-BR")==="empresa"?"Empresa ":""}${labelledCompany[2].trim()}`,labelledCompany[0],.94);
 else if(contextualCompany)out.customer=entity(contextualCompany[1].trim(),contextualCompany[0],.94);
 const payment=/\b(?:cartao(?: de credito)?(?:\s+em\s+(?:\d+|duas|tres)\s*(?:vezes|x))?|pix(?:\s+a\s*vista)?|boleto(?:\s+em\s+(?:\d+|duas|tres)\s*(?:vezes|x))?|dinheiro(?:\s+a\s*vista)?|(?:pagamento\s+)?a\s*vista|pagamento\s+(?:imediato|no\s+ato))\b/iu.exec(plain);if(payment){const details=parsePaymentDetails(payment[0]);out.payment_terms=entity(details?.display??normalizePaymentTerms(payment[0])??payment[0],payment[0]);}
 const explicitValidity=/\b(?:validade|válid[oa]|valid[oa]|vence)\b/iu.test(text);const validity=explicitValidity?parseQuoteValidity(text,today):undefined;if(validity?.success)out.validity=entity(validity.canonical,validity.display,.98);
 const deadline=/(?:\bprazo(?:\s+de\s+(?:entrega|execução|execucao))?\s+(?:de\s+)?|\bentrega\s+em\s+|\bexecut(?:amos|ado|ada)\s+em\s+)(\d{1,4})\s+dias?(?:\s+(úteis|uteis))?/iu.exec(text);if(deadline&&Number(deadline[1])>0)out.requested_date=entity(`${Number(deadline[1])} dias${deadline[2]?" úteis":""}`,deadline[0],.98);
 if(/(?:valor\s+)?(?:de\s+)?cada|valor\s+unitario|(?:por|a)\s+(?:r\$\s*)?[\d.,]+\s*(?:reais?)?\s+cada|por\s+(?:unidade|camera)/.test(plain))out.value_scope=entity("unit","unitário",.98);else if(/valor\s+total|total\s+(?:de|e)|pelo\s+(?:servico\s+todo|pedido\s+inteiro|conjunto)|pedido\s+inteiro\s+por/.test(plain))out.value_scope=entity("total","total",.98);else if(purchaseOrder&&out.quantity&&out.price)out.value_scope=entity("amount_scope_pending","ambíguo",1,true);
 if(/amanha/.test(plain)){const date=new Date(`${today}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+1);out.requested_date=entity(date.toISOString().slice(0,10),"amanhã",.98,true);}if(/sexta/.test(plain))out.requested_date=entity("sexta-feira","sexta",.7,true);
 const doc=/\b(?:orc|pc|os|rel|vis)-?\d[\w-]*/i.exec(text);if(doc)out.document_number=entity(doc[0].toUpperCase(),doc[0]);const period=/ultimos?\s+(7|30)\s+dias|este mes|mes atual/iu.exec(plain);if(period)out.period=entity(period[0],period[0]);return out;
}
export function applyEntitiesToAgentDraft(draft:import("@/lib/ai/contracts").AgentDraft,entities:Record<string,Entity>,type:"quote"|"purchase_order"){const quantity=typeof entities.quantity?.value==="number"?entities.quantity.value:draft.quotedQuantity??undefined,price=typeof entities.price?.value==="number"?entities.price.value:draft.quotedAmount??undefined,candidateDescription=typeof entities.service?.value==="string"?entities.service.value:draft.quotedItemDescription??undefined,description=candidateDescription&&!isPaymentOnlyDescription(candidateDescription)?candidateDescription:undefined,payment=typeof entities.payment_terms?.value==="string"?entities.payment_terms.value:draft.paymentTerms,paymentDetails=payment?parsePaymentDetails(payment):undefined,scope=entities.value_scope?.value??draft.amountScope;const amountScope:"amount_scope_pending"|"unit"|"total"|null=scope==="amount_scope_pending"||scope==="unit"||scope==="total"?scope:null,resolved=amountScope==="unit"||amountScope==="total",unitPrice=resolved&&price&&quantity&&amountScope==="total"?price/quantity:resolved?price:undefined,totalPrice=resolved&&unitPrice&&quantity?unitPrice*quantity:null,normalizedDescription=(description??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR"),product=/\b(?:lampadas?|cadeiras?|notebooks?|materiais?|equipamentos?|produtos?)\b/.test(normalizedDescription),service=/\b(?:instalacao|manutencao|consultoria|design|pintura|servico)\b/.test(normalizedDescription),itemType=description?(product&&!service?"product":service&&!product?"service":product&&service?"mixed":"unknown"):draft.itemType;return{...draft,type,counterpartyName:typeof entities.customer?.value==="string"?entities.customer.value:draft.counterpartyName,paymentTerms:paymentDetails?.display??normalizePaymentTerms(payment),paymentDetails:paymentDetails??draft.paymentDetails,validity:typeof entities.validity?.value==="string"?entities.validity.value:draft.validity,deadline:typeof entities.requested_date?.value==="string"?entities.requested_date.value:draft.deadline,quotedAmount:price??null,amountScope,quotedQuantity:quantity??null,quotedItemDescription:description??draft.quotedItemDescription??null,totalPrice,itemType,items:description&&quantity&&unitPrice?[{description,quantity,unit:"un",unitPrice,discount:0}]:draft.items};}
