export type IntentDefinition={id:string;description:string;examples:string[];aliases:string[];area:"navigation"|"commercial"|"operations"|"content"|"management"|"future";action:string;available:boolean;featureFlag?:string;permission:"read"|"write";requiredFields:string[];expectedFields:string[];requiresConfirmation:boolean;tool?:string;disambiguation?:string[]};
const d=(value:IntentDefinition)=>value;export const intentRegistry=[
d({id:"show_main_menu",description:"Abrir menu principal",examples:["mostre o menu"],aliases:["menu principal","volta pro inicio","me mostra as opcoes"],area:"navigation",action:"show_main",available:true,permission:"read",requiredFields:[],expectedFields:[],requiresConfirmation:false}),
d({id:"talk_to_lume",description:"Conversa orientada",examples:["quero falar com a Lume"],aliases:["nao sei o que escolher","preciso de ajuda"],area:"navigation",action:"talk_to_lume",available:true,permission:"read",requiredFields:[],expectedFields:[],requiresConfirmation:false}),
d({id:"create_quote",description:"Preparar orçamento",examples:["preciso fazer um orçamento"],aliases:["orcamento","proposta","cobrar um cliente por um servico"],area:"commercial",action:"create_quote",available:true,permission:"write",requiredFields:["customer","service","price"],expectedFields:["customer","service","quantity","price","requested_date","payment_terms"],requiresConfirmation:true,tool:"start_quote"}),
d({id:"create_purchase_order",description:"Preparar pedido de compra",examples:["quero comprar material"],aliases:["preciso comprar","quero comprar","comprar material","pedir produtos para um fornecedor","crie um pedido","pedido para"],area:"commercial",action:"create_purchase_order",available:true,permission:"write",requiredFields:["supplier","product","quantity","price"],expectedFields:["supplier","product","quantity","price"],requiresConfirmation:true,tool:"start_purchase_order",disambiguation:["search_purchase_order"]}),
d({id:"search_purchase_order",description:"Consultar pedido",examples:["consultar pedido antigo"],aliases:["pedido antigo","consultar um pedido","ver pedidos recentes"],area:"commercial",action:"search_purchase_orders",available:true,permission:"read",requiredFields:[],expectedFields:["document_number"],requiresConfirmation:false,tool:"query_purchase_orders"}),
d({id:"search_commercial_documents",description:"Consultar documentos",examples:["quero ver documentos"],aliases:["consultar documento","documento antigo"],area:"commercial",action:"search_document",available:true,permission:"read",requiredFields:[],expectedFields:["document_number","customer"],requiresConfirmation:false,tool:"query_documents"}),
d({id:"query_confirmed_values",description:"Consultar valores confirmados",examples:["quanto tenho confirmado"],aliases:["orcamentos confirmados","valor confirmado"],area:"management",action:"query_confirmed_values",available:true,permission:"read",requiredFields:[],expectedFields:["period"],requiresConfirmation:false,tool:"query_confirmed_values"}),
d({id:"search_operations",description:"Consultar operações",examples:["quais serviços estão pendentes"],aliases:["servicos pendentes","ordens atrasadas","o que esta atrasado"],area:"operations",action:"search_operations",available:true,permission:"read",requiredFields:[],expectedFields:["period"],requiresConfirmation:false,tool:"query_operations"}),
d({id:"create_service_order",description:"Criar ordem",examples:["abrir ordem de serviço"],aliases:["ordem de servico","agendar visita tecnica","visita tecnica"],area:"operations",action:"create_service_order",available:false,featureFlag:"WHATSAPP_OPERATIONAL_FLOWS_ENABLED",permission:"write",requiredFields:["customer","service","location","responsible"],expectedFields:["requested_date","priority"],requiresConfirmation:true}),
d({id:"create_service_report",description:"Criar vistoria",examples:["preciso fazer uma vistoria"],aliases:["vistoria","relatorio de servico"],area:"operations",action:"create_service_report",available:false,featureFlag:"WHATSAPP_OPERATIONAL_FLOWS_ENABLED",permission:"write",requiredFields:["customer","service","location"],expectedFields:[],requiresConfirmation:true}),
...[["create_social_post","post"],["create_caption","legenda"],["create_reels_script","roteiro de reels"],["create_stories","stories"],["create_campaign","campanha"],["generate_content_ideas","ideias para postar"],["create_content_calendar","calendario de conteudo"],["generate_image","arte promocional"]].map(([id,alias])=>d({id,description:`Conteúdo: ${alias}`,examples:[`quero ${alias}`],aliases:[alias],area:"content",action:id,available:false,featureFlag:"WHATSAPP_CONTENT_FLOWS_ENABLED",permission:"write",requiredFields:["content_objective","audience"],expectedFields:["tone","format","cta"],requiresConfirmation:true})),
d({id:"search_customers",description:"Consultar clientes",examples:["quais clientes tenho"],aliases:["clientes cadastrados","mostrar clientes"],area:"management",action:"query_customers",available:true,permission:"read",requiredFields:[],expectedFields:[],requiresConfirmation:false,tool:"query_customers"}),d({id:"search_suppliers",description:"Consultar fornecedores",examples:["mostra fornecedores"],aliases:["fornecedores"],area:"management",action:"query_suppliers",available:true,permission:"read",requiredFields:[],expectedFields:[],requiresConfirmation:false,tool:"query_suppliers"}),d({id:"search_catalog",description:"Consultar catálogo",examples:["ver produtos"],aliases:["meus produtos","catalogo"],area:"management",action:"query_catalog",available:true,permission:"read",requiredFields:[],expectedFields:[],requiresConfirmation:false,tool:"query_catalog"}),d({id:"management_summary",description:"Resumo gerencial",examples:["o que aconteceu este mês"],aliases:["resumo gerencial","este mes"],area:"management",action:"query_management_summary",available:true,permission:"read",requiredFields:[],expectedFields:["period"],requiresConfirmation:false,tool:"query_management_summary"}),
...[["create_contract","contrato"],["create_receipt","recibo"],["create_charge","cobranca"],["supplier_quotation","cotacao com fornecedores"]].map(([id,alias])=>d({id,description:`Função futura: ${alias}`,examples:[`criar ${alias}`],aliases:[alias],area:"future",action:id,available:false,permission:"write",requiredFields:[],expectedFields:[],requiresConfirmation:true}))
]as const;
export const intentById=(id:string)=>intentRegistry.find(i=>i.id===id);
