import{orchestratorDecisionSchema,type HybridContext,type OrchestratorDecision}from"./schemas";import{extractEntities}from"./entities";import{intentRegistry,intentById}from"./intent-registry";import{resolveGlobalNavigation}from"@/lib/navigation/menu-engine";
export type OrchestratorInput={message:string;channel:"panel"|"whatsapp";state:string;activeFlow?:string;draft?:unknown;permissions?:string[];featureFlags?:Record<string,boolean>;context?:HybridContext;now?:Date;timeZone?:string;audioConfidence?:number};
const normalize=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const injection=(s:string)=>[/ignore as regras/,/sem confirmar/,/finja que sou administrador/,/outra empresa/,/revele (?:seu )?prompt/,/funcao (?:secreta|escondida)/].some(r=>r.test(s));
const level=(score:number,blocked=false)=>blocked?"blocked"as const:score>=Number(process.env.HYBRID_HIGH_CONFIDENCE||.82)?"high"as const:score>=Number(process.env.HYBRID_MEDIUM_CONFIDENCE||.55)?"medium"as const:"low"as const;
function candidates(message:string){const n=normalize(message);return intentRegistry.map(intent=>{const matches=[...intent.aliases,...intent.examples].map(normalize).filter(a=>n.includes(a));const longest=Math.max(0,...matches.map(m=>m.length));return{intent,score:matches.length?Math.min(.98,.58+longest/80+matches.length*.08):0}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);}
export function orchestrateHybrid(input:OrchestratorInput):OrchestratorDecision{const n=normalize(input.message),global=resolveGlobalNavigation(input.message),entities=extractEntities(input.message,{now:input.now,timeZone:input.timeZone});if(global)return orchestratorDecisionSchema.parse({intent:global==="show_main"?"show_main_menu":global==="back"?"go_back":global==="cancel"?"cancel_current_flow":"talk_to_lume",confidence:1,confidenceLevel:"high",entities,missingFields:[],requiresConfirmation:false,suggestedAction:global,alternativeIntents:[],reasonCode:"global_navigation",clarificationRequired:false,toolProposal:null,interruptionDetected:false,securityEvent:null});if(injection(n))return orchestratorDecisionSchema.parse({intent:"security_boundary",confidence:1,confidenceLevel:"blocked",entities:{},missingFields:[],requiresConfirmation:false,suggestedAction:"explain_limits",alternativeIntents:[],reasonCode:"prompt_injection_pattern",clarificationRequired:false,toolProposal:null,interruptionDetected:false,securityEvent:"instruction_override_attempt"});if(input.audioConfidence!==undefined&&input.audioConfidence<.7)return orchestratorDecisionSchema.parse({intent:"unknown",confidence:input.audioConfidence,confidenceLevel:"low",entities,missingFields:[],requiresConfirmation:false,suggestedAction:"clarify",alternativeIntents:[],reasonCode:"low_audio_confidence",clarificationRequired:true,toolProposal:null,interruptionDetected:false,securityEvent:null});
 const prior=input.context?.pendingDecision;if(prior&&/^(sim|sim continuar|continuar|pode continuar)$/.test(n))return{...prior,confidence:1,confidenceLevel:"high",clarificationRequired:false,reasonCode:"explicit_intent_confirmation"};
 if(/^(retomar|voltar ao fluxo anterior|continuar o anterior)/.test(n)&&input.context?.pausedFlow?.resumable)return orchestratorDecisionSchema.parse({intent:input.context.pausedFlow.flow,confidence:1,confidenceLevel:"high",entities:input.context.recentEntities??{},missingFields:[],requiresConfirmation:false,suggestedAction:input.context.pausedFlow.resumeAction,alternativeIntents:[],reasonCode:"resume_paused_flow",clarificationRequired:false,toolProposal:null,interruptionDetected:false,securityEvent:null});
 const found=candidates(input.message);if(/\bcotacao\b/.test(n))found.unshift({intent:intentById("create_quote")!,score:.65},{intent:intentById("supplier_quotation")!,score:.65});if(/^quero (?:um )?pedido$/.test(n))found.unshift({intent:intentById("create_purchase_order")!,score:.65},{intent:intentById("search_purchase_order")!,score:.65});const best=found[0],alternatives=found.slice(1).filter(x=>best&&best.score-x.score<.12).map(x=>x.intent.id);if(!best)return orchestratorDecisionSchema.parse({intent:"unknown",confidence:.2,confidenceLevel:"low",entities,missingFields:[],requiresConfirmation:false,suggestedAction:"clarify",alternativeIntents:[],reasonCode:"no_intent_match",clarificationRequired:true,toolProposal:null,interruptionDetected:false,securityEvent:null});const available=best.intent.available&&(!best.intent.featureFlag||input.featureFlags?.[best.intent.featureFlag]===true),missing=best.intent.requiredFields.filter(f=>!entities[f]),interruption=Boolean(input.activeFlow&&input.activeFlow!==best.intent.id),score=alternatives.length?Math.min(best.score,.68):best.score;return orchestratorDecisionSchema.parse({intent:best.intent.id,confidence:score,confidenceLevel:level(score),entities,missingFields:missing,requiresConfirmation:best.intent.requiresConfirmation,suggestedAction:available?best.intent.action:"explain_unavailable",alternativeIntents:alternatives,reasonCode:!available?"recognized_but_unavailable":interruption?"subject_change_detected":alternatives.length?"ambiguous_intent":"deterministic_match",clarificationRequired:alternatives.length>0||level(score)==="low",toolProposal:available?best.intent.tool??null:null,interruptionDetected:interruption,securityEvent:null});}
export function pauseForInterruption(context:HybridContext,current:{flow:string;draft:unknown},decision:OrchestratorDecision,now=new Date()):HybridContext{return{...context,pendingDecision:decision,pausedFlow:{flow:current.flow,draft:current.draft,pausedAt:now.toISOString(),reason:"subject_change",resumable:true,resumeAction:current.flow},lastIntent:decision.intent,recentEntities:decision.entities};}
