import { z } from "zod";
import { draftItemV2Schema, taskTypeV2Schema } from "./schema";

export const patchPathV2Schema=z.enum(["draft.party","draft.items","draft.payment","draft.deadline","draft.validity","draft.address","draft.notes"]);
export const patchOperationNameV2Schema=z.enum(["set","unset","append","replace","confirm","invalidate"]);
export const patchOperationV2Schema=z.object({op:patchOperationNameV2Schema,path:patchPathV2Schema,value:z.unknown().optional(),source:z.enum(["user_current_message","user_previous_message","organization","registered_contact","vault","external_lookup","derived_calculation","inference"]),confidence:z.number().min(0).max(1)}).readonly();
export const statePatchV2Schema=z.object({baseRevision:z.number().int().nonnegative(),operations:z.array(patchOperationV2Schema).max(20)}).readonly();
export const interpretationV2Schema=z.object({intent:z.enum(["start_quote","start_purchase_order","continue_task","correct","cancel","switch_task","interrupt","resume","confirm","reject","unknown"]),entities:z.record(z.string(),z.unknown()),correction:z.object({field:patchPathV2Schema,value:z.unknown()}).readonly().nullable(),interruptionIntent:z.enum(["administrative_query","vault_query"]).nullable(),switchIntent:taskTypeV2Schema.nullable(),confidence:z.number().min(0).max(1),rawEvidence:z.array(z.string().max(500)).max(20)}).readonly();
export const boundActionV2Schema=z.object({version:z.literal(2),interactionId:z.string().uuid(),taskId:z.string().uuid(),revision:z.number().int().nonnegative(),actionId:z.string().min(1).max(80)}).readonly();
export const conversationEventV2Schema=z.object({type:z.enum(["INBOUND_TEXT","INBOUND_BUTTON","INBOUND_LIST","INBOUND_FILE","TASK_START","TASK_CANCEL","TASK_SWITCH_REQUESTED","TASK_SWITCH_CONFIRMED","INTERRUPTION_START","INTERRUPTION_COMPLETE","INTERACTION_ANSWERED","CONFIRMATION_REQUESTED","CONFIRMATION_ACCEPTED","CONFIRMATION_REJECTED","EFFECT_STARTED","EFFECT_SUCCEEDED","EFFECT_FAILED","RECOVERY_REQUESTED","SESSION_RESET","STALE_INTERACTION"]),occurredAt:z.string().datetime(),externalMessageId:z.string().max(255).optional(),receivedAt:z.string().datetime().optional(),taskId:z.string().uuid().optional(),taskType:taskTypeV2Schema.optional(),effect:z.enum(["document","pdf","delivery"]).optional(),requestId:z.string().max(240).optional(),resultRef:z.string().max(1000).optional(),error:z.string().max(160).optional(),recoverable:z.boolean().optional(),reason:z.string().max(240).optional(),boundAction:boundActionV2Schema.optional()}).readonly();
export const transitionV2Schema=z.object({nextState:z.unknown(),nextAction:z.string().min(1).max(120),effectsRequested:z.array(z.object({effect:z.enum(["document","pdf","delivery"]),requestId:z.string()})),auditEvents:z.array(z.object({type:z.string(),details:z.record(z.string(),z.unknown())})),rejectedPatchOperations:z.array(z.object({index:z.number().int().nonnegative(),reason:z.string(),operation:patchOperationV2Schema}))});
export type InterpretationV2=z.infer<typeof interpretationV2Schema>;export type StatePatchV2=z.infer<typeof statePatchV2Schema>;export type ConversationEventV2=z.infer<typeof conversationEventV2Schema>;export type BoundActionV2=z.infer<typeof boundActionV2Schema>;
export type DraftItemV2=z.infer<typeof draftItemV2Schema>;
