export type BehaviorCorpusClassification="LEGACY_CORRECT"|"LEGACY_INCORRECT"|"EXPECTED_V2_BEHAVIOR";
export type ShadowComparison="V2_CORRECT_LEGACY_WRONG"|"LEGACY_CORRECT_V2_WRONG"|"BOTH_CORRECT"|"BOTH_WRONG"|"AMBIGUOUS";
export type BehaviorTranscriptV2={id:string;classification:BehaviorCorpusClassification;initialContext:string;inbound:string;expectedInterpretation:string;expectedStateTransition:string;expectedNextAction:string;expectedEffect:string;expectedReply:string;comparison:ShadowComparison;realIncident:boolean};
export const behaviorCorpusV2:readonly BehaviorTranscriptV2[]=Object.freeze([
{id:"quote_alfa_composite",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"idle",inbound:"Preciso fazer um orçamento para a Alfa de 20 lâmpadas a R$30 cada, prazo de 20 dias e pagamento no cartão em 2 vezes.",expectedInterpretation:"start_quote + commercial entities",expectedStateTransition:"idle→quote.collecting",expectedNextAction:"ask only missing validity",expectedEffect:"none",expectedReply:"request validity",comparison:"AMBIGUOUS",realIncident:true},
{id:"short_counterparty",classification:"LEGACY_CORRECT",initialContext:"quote/counterparty",inbound:"Alfa Ltda",expectedInterpretation:"party",expectedStateTransition:"set draft.party; revision++",expectedNextAction:"ask item",expectedEffect:"none",expectedReply:"request product or service",comparison:"BOTH_CORRECT",realIncident:true},
{id:"free_cnpj",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote/tax_id",inbound:"09557452000143",expectedInterpretation:"canonical tax id",expectedStateTransition:"set party.taxId; revision++",expectedNextAction:"next missing field",expectedEffect:"none",expectedReply:"formatted CNPJ",comparison:"BOTH_CORRECT",realIncident:true},
{id:"quantity_correction",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote/correction",inbound:"Na verdade são 30 lâmpadas",expectedInterpretation:"quantity correction",expectedStateTransition:"replace items; invalidate confirmation",expectedNextAction:"request confirmation",expectedEffect:"none",expectedReply:"updated summary",comparison:"AMBIGUOUS",realIncident:true},
{id:"no_thanks",classification:"LEGACY_INCORRECT",initialContext:"active closed choice",inbound:"não, obrigado",expectedInterpretation:"reject current optional interaction",expectedStateTransition:"consume interaction without task contamination",expectedNextAction:"continue or close contextual step",expectedEffect:"none",expectedReply:"contextual acknowledgement",comparison:"V2_CORRECT_LEGACY_WRONG",realIncident:true},
{id:"quote_to_purchase",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote collecting",inbound:"Esquece isso, quero fazer um pedido de compra",expectedInterpretation:"switch_task",expectedStateTransition:"preserve quote + pendingSwitch",expectedNextAction:"confirm switch",expectedEffect:"none",expectedReply:"ask permission to switch",comparison:"BOTH_CORRECT",realIncident:true},
{id:"query_during_quote",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote collecting",inbound:"qual foi meu último pedido?",expectedInterpretation:"administrative interruption",expectedStateTransition:"preserve task and interaction",expectedNextAction:"query",expectedEffect:"query only",expectedReply:"answer + resume choice",comparison:"AMBIGUOUS",realIncident:true},
{id:"resume_after_query",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote interrupted",inbound:"beleza, podemos continuar",expectedInterpretation:"resume",expectedStateTransition:"restore referenced interaction",expectedNextAction:"resume exact question",expectedEffect:"none",expectedReply:"previous question",comparison:"V2_CORRECT_LEGACY_WRONG",realIncident:true},
{id:"ignore_button_text",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"active closed choice",inbound:"pode emitir",expectedInterpretation:"confirmation accepted",expectedStateTransition:"same event as button",expectedNextAction:"document pending",expectedEffect:"document",expectedReply:"processing",comparison:"BOTH_CORRECT",realIncident:true},
{id:"stale_button",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"revision 4 / button revision 3",inbound:"v2 stale action",expectedInterpretation:"stale interaction",expectedStateTransition:"unchanged",expectedNextAction:"refresh interaction",expectedEffect:"none",expectedReply:"choice expired",comparison:"V2_CORRECT_LEGACY_WRONG",realIncident:false},
{id:"document_failure",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"document executing",inbound:"effect failed",expectedInterpretation:"document failure",expectedStateTransition:"document.failed_recoverable + recovery",expectedNextAction:"retry_document",expectedEffect:"none",expectedReply:"data preserved",comparison:"BOTH_CORRECT",realIncident:true},
{id:"pdf_failure",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"document completed/pdf executing",inbound:"effect failed",expectedInterpretation:"pdf failure",expectedStateTransition:"preserve document + pdf recovery",expectedNextAction:"retry_pdf",expectedEffect:"none",expectedReply:"document exists",comparison:"BOTH_CORRECT",realIncident:true},
{id:"outbound_failure",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"document+pdf completed",inbound:"effect failed",expectedInterpretation:"delivery failure",expectedStateTransition:"preserve document/pdf + delivery recovery",expectedNextAction:"retry_delivery",expectedEffect:"none",expectedReply:"PDF ready; retry sending",comparison:"V2_CORRECT_LEGACY_WRONG",realIncident:true},
{id:"first_contact",classification:"LEGACY_CORRECT",initialContext:"idle/no experience",inbound:"Olá",expectedInterpretation:"greeting",expectedStateTransition:"experience timestamp only",expectedNextAction:"await free request",expectedEffect:"none",expectedReply:"introduction",comparison:"BOTH_CORRECT",realIncident:false},
{id:"new_after_completed",classification:"EXPECTED_V2_BEHAVIOR",initialContext:"quote completed",inbound:"Agora preciso fazer um pedido de compra",expectedInterpretation:"explicit new task",expectedStateTransition:"new task id; clean incompatible draft",expectedNextAction:"ask supplier",expectedEffect:"none",expectedReply:"request supplier",comparison:"BOTH_CORRECT",realIncident:true},
]);
export const corpusMetricsV2={realTranscripts:behaviorCorpusV2.filter(item=>item.realIncident).length,knownBadLegacyBehaviors:behaviorCorpusV2.filter(item=>item.classification==="LEGACY_INCORRECT"||item.comparison==="V2_CORRECT_LEGACY_WRONG").length};
