import { agentDraftSchema } from "@/lib/ai/contracts";
import { parsePaymentDetails } from "@/lib/domain/payment-terms";
import { conversationStateV2Schema, createConversationStateV2, type ConversationStateV2 } from "./schema";

export type LegacyV2Classification="VALID"|"MIGRATABLE"|"CONFLICTING"|"STALE"|"CORRUPTED_RECOVERABLE"|"CORRUPTED_FATAL";
const inputName=(value:unknown)=>value==="cliente"||value==="fornecedor"?"counterparty":value==="itens"?"item_bundle":value==="prazo"?"delivery_deadline":value==="condição de pagamento"?"payment":value==="validade"?"validity":value==="endereço de entrega"?"address":value==="correção"?"correction":undefined;
const promptInput=(prompt:Record<string,unknown>|undefined)=>prompt?.promptType==="confirmation"?"confirmation":typeof prompt?.flowId==="string"&&prompt.flowId.includes("cnpj")?"tax_id":undefined;
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export function normalizeLegacyExpectedInput(value:unknown){if(typeof value!=="string")return undefined;return({payment_terms:"payment",quote_validity:"validity",price_scope:"item_bundle",document_selection:"free_text"} as Record<string,string>)[value]??value;}
export function mapLegacyConversationToV2(input:{organizationId:string;conversationKey:string;contactId?:string|null;state?:string;context:unknown;updatedAt?:string;documentStatus?:string|null;now?:string}):{classification:LegacyV2Classification;state?:ConversationStateV2;conflicts:string[];issues:string[]}{const now=input.now??new Date().toISOString(),raw=input.context as {draft?:unknown;documentId?:unknown;collection?:Record<string,unknown>};const parsed=agentDraftSchema.safeParse(raw?.draft);if(!parsed.success)return{classification:"CORRUPTED_FATAL",conflicts:[],issues:parsed.error.issues.map(issue=>issue.path.join("."))};const draft=parsed.data,collection=raw.collection??{},conflicts:string[]=[],issues:string[]=[];const pending=inputName(collection.pendingField),expected=normalizeLegacyExpectedInput(collection.expectedAnswer),prompt=promptInput(collection.activePrompt as Record<string,unknown>|undefined);const declared=[pending,expected,prompt].filter(Boolean);if(new Set(declared).size>1)conflicts.push("LEGACY_INTERACTION_CONFLICT");
  const party=collection.party as Record<string,unknown>|undefined;if(party?.name&&draft.counterpartyName&&party.name!==draft.counterpartyName)conflicts.push("LEGACY_PARTY_CONFLICT");const hybrid=((collection.hybrid as Record<string,unknown>|undefined)?.recentEntities??{}) as Record<string,{value?:unknown}>;if(draft.items[0]&&hybrid.service?.value&&String(hybrid.service.value).toLocaleLowerCase()!==draft.items[0].description.toLocaleLowerCase())conflicts.push("LEGACY_ITEMS_HYBRID_CONFLICT");const summary=collection.summary as {draft?:unknown}|undefined;if(summary?.draft&&!same(summary.draft,draft))conflicts.push("LEGACY_SUMMARY_DRAFT_CONFLICT");if(raw.documentId&&input.documentStatus&&!['draft','confirmed','generated','sent'].includes(input.documentStatus))conflicts.push("LEGACY_DOCUMENT_STATUS_CONFLICT");
  const stale=Boolean(input.updatedAt&&Date.parse(now)-Date.parse(input.updatedAt)>24*60*60*1000);let state=createConversationStateV2({organizationId:input.organizationId,conversationKey:input.conversationKey,contactId:input.contactId,now});const type=draft.type==="quote"||draft.type==="purchase_order"?draft.type:draft.type==="document_search"?"administrative_query":"none";const taskId=state.activeTask.id;const itemType=draft.itemType??"unknown";const payment=parsePaymentDetails(draft.paymentTerms??"");const mappedDraft={party:draft.counterpartyName?{name:draft.counterpartyName,role:type==="purchase_order"?"supplier" as const:"client" as const,source:party?.source==="registered"?"registered" as const:"ad_hoc" as const,...(typeof party?.contactId==="string"?{contactId:party.contactId}:{}),...(typeof party?.taxId==="string"?{taxId:party.taxId}:{})}:null,items:draft.items.map(item=>({...item,itemType})),payment:payment?{method:payment.method,display:payment.display,...(payment.installments?{installments:payment.installments}:{})}:null,deadline:draft.deadline,validity:draft.validity,address:draft.deliveryAddress,notes:draft.notes,provenance:{}};const chosen=declared[0] as "counterparty"|"tax_id"|"item_bundle"|"delivery_deadline"|"payment"|"validity"|"address"|"confirmation"|"correction"|undefined;const interaction=chosen?{id:crypto.randomUUID(),type:chosen==="confirmation"?"confirmation" as const:chosen==="correction"?"correction" as const:"open_input" as const,taskId,revision:0,status:"active" as const,prompt:`Legacy interaction: ${chosen}`,allowedActions:chosen==="confirmation"?["confirm_document","correct_document","cancel_document"]:[],expectedInput:chosen,createdAt:now}:null;state=conversationStateV2Schema.parse({...state,activeTask:{...state.activeTask,type,status:input.state==="confirmed"?"completed":input.state==="cancelled"?"cancelled":input.state==="awaiting_confirmation"?"awaiting_confirmation":type==="none"?"idle":"collecting",updatedAt:now},draft:mappedDraft,interaction,metadata:{...state.metadata,migrationClassification:conflicts.length?"CONFLICTING":stale?"STALE":"MIGRATABLE",legacyConflicts:conflicts}});return{classification:conflicts.length?"CONFLICTING":stale?"STALE":issues.length?"CORRUPTED_RECOVERABLE":"MIGRATABLE",state,conflicts,issues};}
