import {conversationStateV2Schema,type ConversationStateV2} from "./schema";
import type {ConversationQueueStoreV2,LeaseV2,QueueJobV2} from "./queue-contracts";

export class MemoryConversationQueueStoreV2 implements ConversationQueueStoreV2{
  readonly jobs=new Map<string,QueueJobV2>();readonly states=new Map<string,ConversationStateV2>();readonly leases=new Map<string,LeaseV2>();
  constructor(initialStates:ConversationStateV2[]){for(const state of initialStates)this.states.set(state.conversationKey,conversationStateV2Schema.parse(state));}
  async enqueue(input:Omit<QueueJobV2,"status"|"attempts"|"availableAt"|"processingStartedAt"|"completedAt"|"ownerToken"|"leaseExpiresAt"|"errorCode"|"stateRevision">,graceMs:number){if([...this.jobs.values()].some(job=>job.externalMessageId===input.externalMessageId))return"duplicate" as const;this.jobs.set(input.id,{...input,status:"received",attempts:0,availableAt:new Date(Date.parse(input.receivedAt)+graceMs).toISOString(),processingStartedAt:null,completedAt:null,ownerToken:null,leaseExpiresAt:null,errorCode:null,stateRevision:null});return"created" as const;}
  async acquireLease(conversationKey:string,ownerToken:string,now:string,leaseMs:number){const prior=this.leases.get(conversationKey);if(prior&&prior.ownerToken!==ownerToken&&Date.parse(prior.expiresAt)>=Date.parse(now))return false;this.leases.set(conversationKey,{conversationKey,ownerToken,acquiredAt:now,expiresAt:new Date(Date.parse(now)+leaseMs).toISOString()});return true;}
  async renewLease(conversationKey:string,ownerToken:string,now:string,leaseMs:number){const lease=this.leases.get(conversationKey);if(!lease||lease.ownerToken!==ownerToken||Date.parse(lease.expiresAt)<Date.parse(now))return false;this.leases.set(conversationKey,{...lease,expiresAt:new Date(Date.parse(now)+leaseMs).toISOString()});return true;}
  async releaseLease(conversationKey:string,ownerToken:string){if(this.leases.get(conversationKey)?.ownerToken!==ownerToken)return false;this.leases.delete(conversationKey);return true;}
  async claimNext(conversationKey:string,ownerToken:string,now:string){const lease=this.leases.get(conversationKey);if(!lease||lease.ownerToken!==ownerToken||Date.parse(lease.expiresAt)<Date.parse(now))return null;const next=[...this.jobs.values()].filter(job=>job.conversationKey===conversationKey&&["received","ready","deferred","failed_recoverable"].includes(job.status)&&Date.parse(job.availableAt)<=Date.parse(now)).sort((a,b)=>Date.parse(a.receivedAt)-Date.parse(b.receivedAt)||Date.parse(a.createdAt)-Date.parse(b.createdAt)||a.id.localeCompare(b.id))[0];if(!next)return null;const claimed={...next,status:"processing" as const,attempts:next.attempts+1,processingStartedAt:now,ownerToken,leaseExpiresAt:lease.expiresAt};this.jobs.set(next.id,claimed);return structuredClone(claimed);}
  async loadState(conversationKey:string){const state=this.states.get(conversationKey);if(!state)throw new Error("CONVERSATION_V2_STATE_NOT_FOUND");return structuredClone(state);}
  async commitTransition(input:{conversationKey:string;ownerToken:string;jobId:string;expectedRevision:number;nextState:ConversationStateV2;now:string}){const lease=this.leases.get(input.conversationKey),job=this.jobs.get(input.jobId),current=this.states.get(input.conversationKey);if(job?.status==="completed")return"already_completed" as const;if(!lease||lease.ownerToken!==input.ownerToken||Date.parse(lease.expiresAt)<Date.parse(input.now)||job?.ownerToken!==input.ownerToken)return"lease_lost" as const;if(!current||current.revision!==input.expectedRevision)return"cas_conflict" as const;this.states.set(input.conversationKey,conversationStateV2Schema.parse(input.nextState));this.jobs.set(job.id,{...job,status:"completed",completedAt:input.now,errorCode:null,stateRevision:input.nextState.revision,ownerToken:null,leaseExpiresAt:null});return"committed" as const;}
  async defer(jobId:string,ownerToken:string,availableAt:string,errorCode:string){const job=this.jobs.get(jobId);if(job?.ownerToken===ownerToken)this.jobs.set(jobId,{...job,status:"deferred",availableAt,errorCode,ownerToken:null,leaseExpiresAt:null});}
  async fail(jobId:string,ownerToken:string,terminal:boolean,errorCode:string,now:string){const job=this.jobs.get(jobId);if(job?.ownerToken===ownerToken)this.jobs.set(jobId,{...job,status:terminal?"failed_terminal":"failed_recoverable",availableAt:now,errorCode,ownerToken:null,leaseExpiresAt:null});}
  async recover(now:string){let recovered=0;for(const [id,job] of this.jobs){if(job.status==="processing"&&job.leaseExpiresAt&&Date.parse(job.leaseExpiresAt)<Date.parse(now)){this.jobs.set(id,{...job,status:"deferred",availableAt:now,ownerToken:null,leaseExpiresAt:null,errorCode:"STALE_PROCESSING_RECOVERED"});recovered++;}}return recovered;}
  async listConversationKeysWithWork(now:string){return[...new Set([...this.jobs.values()].filter(job=>["received","ready","deferred","failed_recoverable"].includes(job.status)&&Date.parse(job.availableAt)<=Date.parse(now)).map(job=>job.conversationKey))].sort();}
  async getJob(externalMessageId:string){const job=[...this.jobs.values()].find(value=>value.externalMessageId===externalMessageId);return job?structuredClone(job):undefined;}
}
