import { z } from "zod";
import { conversationEventV2Schema, interpretationV2Schema, statePatchV2Schema, type ConversationEventV2, type InterpretationV2, type StatePatchV2 } from "./contracts";
import { conversationStateV2Schema, draftItemV2Schema, provenanceV2Schema, type ConversationStateV2 } from "./schema";
import { validateBoundActionV2 } from "./interaction";

/* eslint-disable prefer-const -- draft binding stays stable while its validated fields are reduced in place. */

const materialPaths=new Set(["draft.party","draft.items","draft.payment","draft.deadline","draft.validity","draft.address","draft.notes"]);
const expectedPaths:Record<string,Set<string>>={counterparty:new Set(["draft.party"]),tax_id:new Set(["draft.party"]),item_bundle:new Set(["draft.items"]),delivery_deadline:new Set(["draft.deadline"]),payment:new Set(["draft.payment"]),validity:new Set(["draft.validity"]),address:new Set(["draft.address"]),correction:new Set(materialPaths),free_text:new Set(materialPaths),none:new Set(),confirmation:new Set()};
const valueSchemas:Record<string,z.ZodType>={"draft.party":z.object({name:z.string().trim().min(2).max(160),role:z.enum(["client","supplier"]),source:z.enum(["registered","ad_hoc"]),contactId:z.string().uuid().optional(),taxId:z.string().max(20).optional()}),"draft.items":z.array(draftItemV2Schema),"draft.payment":z.object({method:z.enum(["pix","cash","boleto","credit_card","debit_card","bank_transfer","other"]),display:z.string().min(1).max(200),installments:z.number().int().positive().optional()}),"draft.deadline":z.string().max(120),"draft.validity":z.string().max(120),"draft.address":z.string().max(500),"draft.notes":z.string().max(2000)};
const emptyEffect=()=>({status:"not_requested" as const,requestId:null,resultRef:null,startedAt:null,completedAt:null,error:null});
const fingerprint=(value:unknown)=>{const text=JSON.stringify(value);let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return `v2-${(hash>>>0).toString(16).padStart(8,"0")}`;};
const deterministicUuid=(seed:string)=>{const h=(part:string)=>fingerprint(part).slice(3).padStart(8,"0");const raw=`${h(seed)}${h(seed+"a")}${h(seed+"b")}${h(seed+"c")}`.slice(0,32);return `${raw.slice(0,8)}-${raw.slice(8,12)}-4${raw.slice(13,16)}-8${raw.slice(17,20)}-${raw.slice(20,32)}`;};
const interactionFor=(state:ConversationStateV2,input:{type:"open_input"|"closed_choice"|"confirmation"|"correction"|"resume"|"intent_switch"|"recovery";expectedInput:"document_type"|"counterparty"|"tax_id"|"item_bundle"|"delivery_deadline"|"payment"|"validity"|"address"|"confirmation"|"correction"|"free_text"|"none";prompt:string;actions?:string[];now:string})=>({id:deterministicUuid(`${state.activeTask.id}:${state.revision}:${input.type}:${input.expectedInput}`),type:input.type,taskId:state.activeTask.type==="none"?null:state.activeTask.id,revision:state.revision,status:"active" as const,prompt:input.prompt,allowedActions:input.actions??[],expectedInput:input.expectedInput,createdAt:input.now});
const nextExpected=(state:ConversationStateV2)=>!state.draft.party?{input:"counterparty" as const,prompt:"Qual é a contraparte?"}:!state.draft.items.length?{input:"item_bundle" as const,prompt:"Qual é o produto ou serviço?"}:!state.draft.deadline?{input:"delivery_deadline" as const,prompt:"Qual é o prazo?"}:!state.draft.payment?{input:"payment" as const,prompt:"Como será o pagamento?"}:state.activeTask.type==="quote"&&!state.draft.validity?{input:"validity" as const,prompt:"Qual é a validade?"}:state.activeTask.type==="purchase_order"&&!state.draft.address?{input:"address" as const,prompt:"Qual é o endereço de entrega?"}:null;

function applyPatch(state:ConversationStateV2,patch:StatePatchV2,event:ConversationEventV2){const rejected:Array<{index:number;reason:string;operation:StatePatchV2["operations"][number]}>=[];if(patch.baseRevision!==state.revision)return{state,rejected:patch.operations.map((operation,index)=>({index,reason:"STALE_BASE_REVISION",operation})),material:false};let draft:Record<string,unknown>={...state.draft,provenance:{...state.draft.provenance}},material=false;const allowed=state.interaction?.status==="active"?expectedPaths[state.interaction.expectedInput]??new Set<string>():new Set<string>();patch.operations.forEach((operation,index)=>{if(!materialPaths.has(operation.path)){rejected.push({index,reason:"PATH_NOT_ALLOWED",operation});return;}if(!allowed.has(operation.path)){rejected.push({index,reason:"INTERACTION_PATH_MISMATCH",operation});return;}const key=operation.path.slice("draft.".length);if(operation.op==="unset"){draft[key]=key==="items"?[]:null;material=true;}else if(operation.op==="append"&&key==="items"){const parsed=draftItemV2Schema.safeParse(operation.value);if(!parsed.success){rejected.push({index,reason:"INVALID_VALUE",operation});return;}draft.items=[...(draft.items as unknown[]),parsed.data];material=true;}else if(operation.op==="set"||operation.op==="replace"){const parsed=valueSchemas[operation.path].safeParse(operation.value);if(!parsed.success){rejected.push({index,reason:"INVALID_VALUE",operation});return;}draft[key]=parsed.data;material=true;}else if(operation.op==="confirm"){const current=(draft.provenance as Record<string,unknown>)[operation.path];if(!current){rejected.push({index,reason:"NO_PROVENANCE_TO_CONFIRM",operation});return;}(draft.provenance as Record<string,unknown>)[operation.path]={...(current as object),status:"CONFIRMED",timestamp:event.occurredAt};}else if(operation.op==="invalidate"){draft[key]=key==="items"?[]:null;material=true;}else rejected.push({index,reason:"OPERATION_NOT_COMPATIBLE",operation});if(!rejected.some(item=>item.index===index)&&(operation.op==="set"||operation.op==="replace"||operation.op==="append")){(draft.provenance as Record<string,unknown>)[operation.path]=provenanceV2Schema.parse({source:operation.source,confidence:operation.confidence,status:operation.confidence===1?"KNOWN":operation.confidence>=.8?"INFERRED":"UNCERTAIN",timestamp:event.occurredAt});}});return{state:conversationStateV2Schema.parse({...state,draft}),rejected,material};}

export function reduceConversationV2(current:ConversationStateV2,eventInput:ConversationEventV2,interpretationInput:InterpretationV2,patchInput:StatePatchV2){const event=conversationEventV2Schema.parse(eventInput),interpretation=interpretationV2Schema.parse(interpretationInput),patch=statePatchV2Schema.parse(patchInput);let state=conversationStateV2Schema.parse(current);const auditEvents:Array<{type:string;details:Record<string,unknown>}>=[],effectsRequested:Array<{effect:"document"|"pdf"|"delivery";requestId:string}>=[];let rejectedPatchOperations:Array<{index:number;reason:string;operation:StatePatchV2["operations"][number]}>=[],nextAction="NOOP";
  if(event.boundAction){const valid=validateBoundActionV2(state,event.boundAction);if(!valid.valid)return{nextState:state,nextAction:"STALE_INTERACTION",effectsRequested,auditEvents:[{type:"stale_action_rejected",details:{reason:valid.reason}}],rejectedPatchOperations};}
  if(event.type==="SESSION_RESET"){const fresh={...state,revision:state.revision+1,activeTask:{...state.activeTask,type:"none" as const,status:"idle" as const,updatedAt:event.occurredAt},draft:{party:null,items:[],payment:null,deadline:null,validity:null,address:null,notes:null,provenance:{}},interaction:null,interruption:null,pendingSwitch:null,confirmation:null,recovery:null,effects:{document:emptyEffect(),pdf:emptyEffect(),delivery:emptyEffect()}};state=conversationStateV2Schema.parse(fresh);nextAction="SESSION_READY";}
  else if(event.type==="TASK_START"&&event.taskType&&event.taskType!=="none"){const revision=state.revision+1;state=conversationStateV2Schema.parse({...state,revision,activeTask:{id:event.taskId??deterministicUuid(`${event.externalMessageId??event.occurredAt}:${event.taskType}`),type:event.taskType,status:"collecting",startedAt:event.occurredAt,updatedAt:event.occurredAt},draft:{party:null,items:[],payment:null,deadline:null,validity:null,address:null,notes:null,provenance:{}},confirmation:null,recovery:null,pendingSwitch:null,interruption:null,effects:{document:emptyEffect(),pdf:emptyEffect(),delivery:emptyEffect()}});state=conversationStateV2Schema.parse({...state,interaction:interactionFor(state,{type:"open_input",expectedInput:"counterparty",prompt:"Qual é a contraparte?",now:event.occurredAt})});nextAction="ASK_COUNTERPARTY";}
  else if(event.type==="TASK_CANCEL"){state=conversationStateV2Schema.parse({...state,revision:state.revision+1,activeTask:{...state.activeTask,status:"cancelled",updatedAt:event.occurredAt},interaction:null,recovery:null});nextAction="TASK_CANCELLED";}
  else if(event.type==="TASK_SWITCH_REQUESTED"&&event.taskType){state=conversationStateV2Schema.parse({...state,pendingSwitch:{fromTask:state.activeTask.type,toTask:event.taskType,reason:event.reason??"user_requested",status:"pending"},interaction:interactionFor(state,{type:"intent_switch",expectedInput:"confirmation",prompt:"Deseja trocar de tarefa?",actions:["confirm_switch","keep_current"],now:event.occurredAt})});nextAction="CONFIRM_TASK_SWITCH";}
  else if(event.type==="TASK_SWITCH_CONFIRMED"&&state.pendingSwitch){const revision=state.revision+1,to=state.pendingSwitch.toTask;state=conversationStateV2Schema.parse({...state,revision,activeTask:{id:event.taskId??deterministicUuid(`${state.activeTask.id}:${revision}:${to}`),type:to,status:"collecting",startedAt:event.occurredAt,updatedAt:event.occurredAt},draft:{party:null,items:[],payment:null,deadline:null,validity:null,address:null,notes:null,provenance:{}},pendingSwitch:null,confirmation:null,recovery:null,effects:{document:emptyEffect(),pdf:emptyEffect(),delivery:emptyEffect()}});state=conversationStateV2Schema.parse({...state,interaction:interactionFor(state,{type:"open_input",expectedInput:"counterparty",prompt:"Qual é a contraparte?",now:event.occurredAt})});nextAction="ASK_COUNTERPARTY";}
  else if(event.type==="INTERRUPTION_START"&&(interpretation.interruptionIntent||event.taskType==="administrative_query"||event.taskType==="vault_query")){state=conversationStateV2Schema.parse({...state,interruption:{type:interpretation.interruptionIntent??(event.taskType as "administrative_query"|"vault_query"),status:"active",startedAt:event.occurredAt,resumeTaskId:state.activeTask.id,resumeRevision:state.revision,resumeInteraction:state.interaction},interaction:interactionFor(state,{type:"resume",expectedInput:"none",prompt:"Consulta em andamento",actions:[],now:event.occurredAt})});nextAction="EXECUTE_INTERRUPTION_QUERY";}
  else if(event.type==="INTERRUPTION_COMPLETE"&&state.interruption){state=conversationStateV2Schema.parse({...state,interaction:state.interruption.resumeInteraction,interruption:null});nextAction="RESUME_PREVIOUS_INTERACTION";}
  else if(event.type==="CONFIRMATION_REQUESTED"){state=conversationStateV2Schema.parse({...state,activeTask:{...state.activeTask,status:"awaiting_confirmation",updatedAt:event.occurredAt},confirmation:{taskId:state.activeTask.id,revision:state.revision,snapshot:state.draft,fingerprint:fingerprint(state.draft),status:"pending",requestedAt:event.occurredAt,confirmedAt:null},interaction:interactionFor(state,{type:"confirmation",expectedInput:"confirmation",prompt:"Confirma os dados?",actions:["confirm_document","correct_document","cancel_document"],now:event.occurredAt})});nextAction="PRESENT_CONFIRMATION";}
  else if(event.type==="CONFIRMATION_ACCEPTED"){if(!state.confirmation||state.confirmation.status!=="pending"||state.confirmation.revision!==state.revision){nextAction="STALE_CONFIRMATION";auditEvents.push({type:"confirmation_rejected",details:{reason:"revision_mismatch"}});}else{const requestId=`${state.activeTask.id}:${state.revision}:document`;state=conversationStateV2Schema.parse({...state,activeTask:{...state.activeTask,status:"executing",updatedAt:event.occurredAt},confirmation:{...state.confirmation,status:"confirmed",confirmedAt:event.occurredAt},interaction:null,effects:{...state.effects,document:{...state.effects.document,status:"pending",requestId}}});effectsRequested.push({effect:"document",requestId});nextAction="EXECUTE_DOCUMENT";}}
  else if(event.type==="CONFIRMATION_REJECTED"){state=conversationStateV2Schema.parse({...state,confirmation:state.confirmation?{...state.confirmation,status:"rejected"}:null,interaction:interactionFor(state,{type:"correction",expectedInput:"correction",prompt:"O que deseja corrigir?",now:event.occurredAt}),activeTask:{...state.activeTask,status:"collecting",updatedAt:event.occurredAt}});nextAction="ASK_CORRECTION";}
  else if(event.type==="EFFECT_STARTED"&&event.effect){const prior=state.effects[event.effect];if(prior.status!=="completed")state=conversationStateV2Schema.parse({...state,effects:{...state.effects,[event.effect]:{...prior,status:"executing",requestId:event.requestId??prior.requestId,startedAt:event.occurredAt,error:null}}});nextAction=`WAIT_${event.effect.toUpperCase()}`;}
  else if(event.type==="EFFECT_SUCCEEDED"&&event.effect){const prior=state.effects[event.effect];state=conversationStateV2Schema.parse({...state,effects:{...state.effects,[event.effect]:{...prior,status:"completed",requestId:event.requestId??prior.requestId,resultRef:event.resultRef??prior.resultRef,completedAt:event.occurredAt,error:null}},recovery:null});nextAction=event.effect==="document"?"REQUEST_PDF":event.effect==="pdf"?"REQUEST_DELIVERY":"COMPLETE_TASK";}
  else if(event.type==="EFFECT_FAILED"&&event.effect){const prior=state.effects[event.effect];if(prior.status!=="completed")state=conversationStateV2Schema.parse({...state,effects:{...state.effects,[event.effect]:{...prior,status:event.recoverable===false?"failed_terminal":"failed_recoverable",error:event.error??"UNKNOWN",completedAt:event.occurredAt}},recovery:{stage:event.effect,reason:event.error??"UNKNOWN",recoverable:event.recoverable!==false,nextAllowedActions:event.recoverable===false?["cancel"]:[`retry_${event.effect}`,"cancel"]},interaction:interactionFor(state,{type:"recovery",expectedInput:"confirmation",prompt:"A etapa falhou. Deseja tentar novamente?",actions:event.recoverable===false?["cancel"]:[`retry_${event.effect}`,"cancel"],now:event.occurredAt})});nextAction="PRESENT_RECOVERY";}
  else {const applied=applyPatch(state,patch,event);state=applied.state;rejectedPatchOperations=applied.rejected;if(applied.material){const revision=state.revision+1;state=conversationStateV2Schema.parse({...state,revision,confirmation:state.confirmation?{...state.confirmation,status:"invalidated"}:null,interaction:null,activeTask:{...state.activeTask,status:"collecting",updatedAt:event.occurredAt}});const expected=nextExpected(state);state=conversationStateV2Schema.parse({...state,interaction:expected?interactionFor(state,{type:interpretation.intent==="correct"?"correction":"open_input",expectedInput:expected.input,prompt:expected.prompt,now:event.occurredAt}):null});nextAction=expected?`ASK_${expected.input.toUpperCase()}`:"REQUEST_CONFIRMATION";}else nextAction=rejectedPatchOperations.length?"CLARIFY_REJECTED_PATCH":"NOOP";}
  if(event.externalMessageId&&event.receivedAt)state=conversationStateV2Schema.parse({...state,lastProcessedEvent:{externalMessageId:event.externalMessageId,receivedAt:event.receivedAt,processedAt:event.occurredAt,stateRevision:state.revision}});state=conversationStateV2Schema.parse({...state,metadata:{...state.metadata,updatedAt:event.occurredAt}});return{nextState:state,nextAction,effectsRequested,auditEvents,rejectedPatchOperations};}

export const CONVERSATION_V2_TRANSITIONS=Object.freeze({TASK_START:"idle × TASK_START → collecting + open_input",TASK_SWITCH_REQUESTED:"active × TASK_SWITCH_REQUESTED → preserve draft + intent_switch",INTERRUPTION_START:"active × INTERRUPTION_START → preserve task/interaction + interruption",CONFIRMATION_REQUESTED:"collecting × CONFIRMATION_REQUESTED → revision-bound confirmation",CONFIRMATION_ACCEPTED:"matching confirmation × ACCEPTED → document pending",EFFECT_FAILED:"effect incomplete × FAILED → explicit recovery",SESSION_RESET:"any × SESSION_RESET → idle clean state"});
