import { z } from "zod";

export const CONVERSATION_STATE_V2_VERSION = 2 as const;
export const taskTypeV2Schema = z.enum(["quote","purchase_order","administrative_query","vault_query","branding","none"]);
export const taskStatusV2Schema = z.enum(["idle","collecting","awaiting_confirmation","executing","completed","cancelled"]);
export const provenanceV2Schema = z.object({source:z.enum(["user_current_message","user_previous_message","organization","registered_contact","vault","external_lookup","derived_calculation","inference"]),confidence:z.number().min(0).max(1),status:z.enum(["KNOWN","INFERRED","UNCERTAIN","MISSING","CONFIRMED"]),timestamp:z.string().datetime()}).readonly();
export const draftItemV2Schema=z.object({description:z.string().trim().min(1).max(500),quantity:z.number().positive(),unit:z.string().trim().min(1).max(20),unitPrice:z.number().nonnegative(),discount:z.number().min(0).default(0),itemType:z.enum(["product","service","mixed","unknown"])}).readonly();
export const draftV2Schema=z.object({party:z.object({name:z.string().trim().min(2).max(160),role:z.enum(["client","supplier"]),source:z.enum(["registered","ad_hoc"]),contactId:z.string().uuid().optional(),taxId:z.string().max(20).optional()}).readonly().nullable(),items:z.array(draftItemV2Schema),payment:z.object({method:z.enum(["pix","cash","boleto","credit_card","debit_card","bank_transfer","other"]),display:z.string().min(1).max(200),installments:z.number().int().positive().optional()}).readonly().nullable(),deadline:z.string().max(120).nullable(),validity:z.string().max(120).nullable(),address:z.string().max(500).nullable(),notes:z.string().max(2000).nullable(),provenance:z.record(z.string(),provenanceV2Schema)}).readonly();
export const activeTaskV2Schema=z.object({id:z.string().uuid(),type:taskTypeV2Schema,status:taskStatusV2Schema,startedAt:z.string().datetime(),updatedAt:z.string().datetime()}).readonly();
export const interactionTypeV2Schema=z.enum(["open_input","closed_choice","confirmation","correction","resume","intent_switch","recovery"]);
export const interactionV2Schema=z.object({id:z.string().uuid(),type:interactionTypeV2Schema,taskId:z.string().uuid().nullable(),revision:z.number().int().nonnegative(),status:z.enum(["active","consumed","expired","cancelled"]),prompt:z.string().min(1).max(2000),allowedActions:z.array(z.string().min(1).max(80)).max(12),expectedInput:z.enum(["document_type","counterparty","tax_id","item_bundle","delivery_deadline","payment","validity","address","confirmation","correction","free_text","none"]),createdAt:z.string().datetime(),expiresAt:z.string().datetime().optional(),consumedAt:z.string().datetime().optional()}).readonly();
export const effectStatusV2Schema=z.enum(["not_requested","pending","executing","completed","failed_recoverable","failed_terminal"]);
export const effectCheckpointV2Schema=z.object({status:effectStatusV2Schema,requestId:z.string().max(240).nullable(),resultRef:z.string().max(1000).nullable(),startedAt:z.string().datetime().nullable(),completedAt:z.string().datetime().nullable(),error:z.string().max(160).nullable()}).readonly();
const confirmationV2Schema=z.object({taskId:z.string().uuid(),revision:z.number().int().nonnegative(),snapshot:draftV2Schema,fingerprint:z.string().min(1).max(128),status:z.enum(["pending","confirmed","rejected","invalidated"]),requestedAt:z.string().datetime(),confirmedAt:z.string().datetime().nullable()}).readonly();
const pendingSwitchV2Schema=z.object({fromTask:taskTypeV2Schema,toTask:taskTypeV2Schema,reason:z.string().min(1).max(240),status:z.enum(["pending","confirmed","cancelled"])}).readonly();
const interruptionV2Schema=z.object({type:z.enum(["administrative_query","vault_query"]),status:z.enum(["active","completed","cancelled"]),startedAt:z.string().datetime(),resumeTaskId:z.string().uuid(),resumeRevision:z.number().int().nonnegative(),resumeInteraction:interactionV2Schema.nullable()}).readonly();
const recoveryV2Schema=z.object({stage:z.enum(["document","pdf","delivery","conversation"]),reason:z.string().min(1).max(160),recoverable:z.boolean(),nextAllowedActions:z.array(z.string().min(1).max(80)).max(8)}).readonly();
const eventCursorV2Schema=z.object({externalMessageId:z.string().min(1).max(255),receivedAt:z.string().datetime(),processedAt:z.string().datetime(),stateRevision:z.number().int().nonnegative()}).readonly();

export const conversationStateV2Schema=z.object({version:z.literal(CONVERSATION_STATE_V2_VERSION),revision:z.number().int().nonnegative(),organizationId:z.string().uuid(),contactId:z.string().max(255).nullable(),channel:z.literal("whatsapp"),conversationKey:z.string().min(1).max(500),activeTask:activeTaskV2Schema,draft:draftV2Schema,interaction:interactionV2Schema.nullable(),interruption:interruptionV2Schema.nullable(),pendingSwitch:pendingSwitchV2Schema.nullable(),confirmation:confirmationV2Schema.nullable(),effects:z.object({document:effectCheckpointV2Schema,pdf:effectCheckpointV2Schema,delivery:effectCheckpointV2Schema}).readonly(),recovery:recoveryV2Schema.nullable(),experience:z.object({introductionSeenAt:z.string().datetime().nullable(),lastInteractionAt:z.string().datetime().nullable()}).readonly(),lastProcessedEvent:eventCursorV2Schema.nullable(),metadata:z.object({createdAt:z.string().datetime(),updatedAt:z.string().datetime(),migrationClassification:z.string().max(80).nullable(),legacyConflicts:z.array(z.string().max(160))}).readonly()}).readonly();
export type ConversationStateV2=z.infer<typeof conversationStateV2Schema>;

const emptyEffect=()=>({status:"not_requested" as const,requestId:null,resultRef:null,startedAt:null,completedAt:null,error:null});
export function createConversationStateV2(input:{organizationId:string;conversationKey:string;contactId?:string|null;now?:string}):ConversationStateV2{const now=input.now??new Date().toISOString();return conversationStateV2Schema.parse({version:2,revision:0,organizationId:input.organizationId,contactId:input.contactId??null,channel:"whatsapp",conversationKey:input.conversationKey,activeTask:{id:crypto.randomUUID(),type:"none",status:"idle",startedAt:now,updatedAt:now},draft:{party:null,items:[],payment:null,deadline:null,validity:null,address:null,notes:null,provenance:{}},interaction:null,interruption:null,pendingSwitch:null,confirmation:null,effects:{document:emptyEffect(),pdf:emptyEffect(),delivery:emptyEffect()},recovery:null,experience:{introductionSeenAt:null,lastInteractionAt:null},lastProcessedEvent:null,metadata:{createdAt:now,updatedAt:now,migrationClassification:null,legacyConflicts:[]}});}
