import { conversationEventV2Schema, statePatchV2Schema } from "./contracts";
import { interpretInboundV2 } from "./interpreter";
import { mapLegacyConversationToV2 } from "./legacy-mapper";
import { reduceConversationV2 } from "./reducer";

export type ConversationV2ShadowAudit={classification:string;conflicts:string[];legacy:{state:string;intent:string|null;nextAction:string|null;effect:string|null};v2:{state:string;intent:string;nextAction:string;interaction:string|null;effects:string[]};divergences:string[];sideEffects:false};
export function runConversationV2Shadow(input:{organizationId:string;conversationKey:string;contactId?:string|null;legacyState:string;legacyContext:unknown;inbound:{text:string;externalMessageId:string;receivedAt:string};legacyResult:{state:string;draft?:{type?:string|null};collection?:{activeTask?:{type?:string;nextAction?:string}};documentId?:string}}):ConversationV2ShadowAudit{const mapped=mapLegacyConversationToV2({organizationId:input.organizationId,conversationKey:input.conversationKey,contactId:input.contactId,state:input.legacyState,context:input.legacyContext,now:input.inbound.receivedAt});if(!mapped.state)return{classification:mapped.classification,conflicts:mapped.conflicts,legacy:{state:input.legacyResult.state,intent:input.legacyResult.draft?.type??null,nextAction:input.legacyResult.collection?.activeTask?.nextAction??null,effect:input.legacyResult.documentId?"document":null},v2:{state:"unavailable",intent:"unknown",nextAction:"NONE",interaction:null,effects:[]},divergences:["V2_MAPPING_FAILED"],sideEffects:false};let state=mapped.state;const understood=interpretInboundV2(state,input.inbound.text);let eventType:"INBOUND_TEXT"|"TASK_START"|"TASK_CANCEL"|"TASK_SWITCH_REQUESTED"|"INTERRUPTION_START"|"INTERRUPTION_COMPLETE"|"CONFIRMATION_ACCEPTED"="INBOUND_TEXT",taskType:undefined|"quote"|"purchase_order"|"administrative_query"|"vault_query";
  if(understood.interpretation.intent==="start_quote"){eventType="TASK_START";taskType="quote";}else if(understood.interpretation.intent==="start_purchase_order"){eventType="TASK_START";taskType="purchase_order";}else if(understood.interpretation.intent==="cancel")eventType="TASK_CANCEL";else if(understood.interpretation.intent==="switch_task"){eventType="TASK_SWITCH_REQUESTED";taskType=understood.interpretation.switchIntent==="purchase_order"?"purchase_order":"quote";}else if(understood.interpretation.intent==="interrupt"){eventType="INTERRUPTION_START";taskType=understood.interpretation.interruptionIntent??"administrative_query";}else if(understood.interpretation.intent==="resume")eventType="INTERRUPTION_COMPLETE";else if(understood.interpretation.intent==="confirm")eventType="CONFIRMATION_ACCEPTED";
  const event=conversationEventV2Schema.parse({type:eventType,occurredAt:input.inbound.receivedAt,receivedAt:input.inbound.receivedAt,externalMessageId:input.inbound.externalMessageId,taskType});const transition=reduceConversationV2(state,event,understood.interpretation,eventType==="INBOUND_TEXT"?understood.patch:statePatchV2Schema.parse({baseRevision:state.revision,operations:[]}));state=transition.nextState;const legacyIntent=input.legacyResult.draft?.type??input.legacyResult.collection?.activeTask?.type??null,v2Intent=state.activeTask.type;const divergences=[...(legacyIntent&&legacyIntent!==v2Intent?["INTENT"]:[]),...(input.legacyResult.state!==state.activeTask.status?["STATE"]:[]),...(mapped.conflicts.length?["LEGACY_CONFLICTS"]:[])];return{classification:mapped.classification,conflicts:mapped.conflicts,legacy:{state:input.legacyResult.state,intent:legacyIntent,nextAction:input.legacyResult.collection?.activeTask?.nextAction??null,effect:input.legacyResult.documentId?"document":null},v2:{state:state.activeTask.status,intent:v2Intent,nextAction:transition.nextAction,interaction:state.interaction?.expectedInput??null,effects:transition.effectsRequested.map(effect=>effect.effect)},divergences,sideEffects:false};}
