import { describe,expect,it,vi } from "vitest";
import { processAgentV1Turn } from "@/lib/agent-v1/processor";
import { encodeBoundAction } from "@/lib/agent-v1/interactions";
const tools=()=>({create_quote:vi.fn(async(_task,requestId)=>({resultRef:`quote:${requestId}`})),create_purchase_order:vi.fn(async(_task,requestId)=>({resultRef:`purchase:${requestId}`})),find_organization_tax_id:vi.fn(async()=>({resultRef:"CNPJ 00.000.000/0001-00"})),search_vault:vi.fn(async()=>({resultRef:"Contrato Alfa"}))});
describe("processor exclusivo Agent V1",()=>{
 it("não invoca autoridades legadas e emite uma única vez por botão ou retry",async()=>{const registry=tools();let out=await processAgentV1Turn({message:"Preciso fazer um orçamento para a empresa Alfa de 20 lâmpadas a R$30 cada, prazo de 20 dias, cartão em 2 vezes e validade de 30 dias.",today:"2026-08-12",tools:registry});expect(out.legacyAuthorityInvoked).toBe(false);expect(out.task.currentQuestion?.type).toBe("confirm_document");const button=encodeBoundAction({actionId:"confirm_document",taskId:out.task.id,revision:out.task.revision});out=await processAgentV1Turn({message:"Emitir",buttonId:button,task:out.task,today:"2026-08-12",tools:registry});expect(out.task.status).toBe("completed");expect(registry.create_quote).toHaveBeenCalledTimes(1);const retry=await processAgentV1Turn({message:"Emitir",buttonId:button,task:out.task,today:"2026-08-12",tools:registry});expect(retry.legacyAuthorityInvoked).toBe(false);expect(registry.create_quote).toHaveBeenCalledTimes(1);});
 it("preserva tarefa em consulta e retoma a pergunta exata",async()=>{const registry=tools();const active=await processAgentV1Turn({message:"Preciso fazer um orçamento para a empresa Alfa de 20 lâmpadas a R$30 cada",today:"2026-08-12",tools:registry}),question=active.task.currentQuestion;const query=await processAgentV1Turn({message:"Antes, qual é o CNPJ da minha empresa?",task:active.task,today:"2026-08-12",tools:registry});expect(query.task.collectedData).toEqual(active.task.collectedData);expect(query.task.interruption?.resumeQuestion).toEqual(question);expect(registry.find_organization_tax_id).toHaveBeenCalledTimes(1);const resumeId=encodeBoundAction({actionId:"resume_task",taskId:query.task.id,revision:query.task.revision}),resumed=await processAgentV1Turn({message:"Continuar",buttonId:resumeId,task:query.task,today:"2026-08-12",tools:registry});expect(resumed.task.currentQuestion).toEqual(question);expect(resumed.task.interruption).toBeNull();});
 it("menu e saudação não alteram tarefa",async()=>{const registry=tools(),active=await processAgentV1Turn({message:"Preciso fazer um orçamento para a empresa Alfa de 20 lâmpadas a R$30 cada",today:"2026-08-12",tools:registry});for(const message of ["Menu","Boa tarde"]){const response=await processAgentV1Turn({message,task:active.task,today:"2026-08-12",tools:registry});expect(response.task).toEqual(active.task);expect(response.legacyAuthorityInvoked).toBe(false);}});
});
