import {describe,expect,it} from "vitest";
import {createConversationStateV2,conversationStateV2Schema} from "@/lib/conversation-v2/schema";
import {reduceConversationV2,CONVERSATION_V2_TRANSITIONS} from "@/lib/conversation-v2/reducer";
import {interpretationV2Schema,statePatchV2Schema} from "@/lib/conversation-v2/contracts";
import {encodeBoundActionV2,decodeBoundActionV2} from "@/lib/conversation-v2/interaction";

const now="2026-08-16T12:00:00.000Z",org="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",task="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const interpretation=(intent="continue_task")=>interpretationV2Schema.parse({intent,entities:{},correction:null,interruptionIntent:null,switchIntent:null,confidence:1,rawEvidence:[intent]});
const patch=(revision:number,operations:unknown[]=[])=>statePatchV2Schema.parse({baseRevision:revision,operations});
const event=(type:string,extra:Record<string,unknown>={})=>({type,occurredAt:now,externalMessageId:`wamid.${type}`,receivedAt:now,...extra} as never);
const started=()=>reduceConversationV2(createConversationStateV2({organizationId:org,conversationKey:"wa:1",now}),event("TASK_START",{taskType:"quote",taskId:task}),interpretation("start_quote"),patch(0)).nextState;

describe("ConversationStateV2 foundation",()=>{
  it("produces the same transition for the same input",()=>{const state=started(),p=patch(state.revision,[{op:"set",path:"draft.party",value:{name:"Alfa",role:"client",source:"ad_hoc"},source:"user_current_message",confidence:.99}]);const a=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation(),p),b=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation(),p);expect(a).toEqual(b);expect(a.nextState.revision).toBe(state.revision+1);});
  it("whitelists patch paths, types and active interaction",()=>{const state=started(),result=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation(),patch(state.revision,[{op:"set",path:"draft.payment",value:{method:"pix",display:"PIX"},source:"user_current_message",confidence:1}]));expect(result.nextState.draft).toEqual(state.draft);expect(result.nextState.revision).toBe(state.revision);expect(result.rejectedPatchOperations[0].reason).toBe("INTERACTION_PATH_MISMATCH");});
  it("rejects stale patch revisions",()=>{const state=started(),result=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation(),patch(0,[{op:"set",path:"draft.party",value:{name:"Alfa",role:"client",source:"ad_hoc"},source:"user_current_message",confidence:1}]));expect(result.rejectedPatchOperations[0].reason).toBe("STALE_BASE_REVISION");});
  it("binds actions to interaction, task and revision",()=>{const state=started(),active=state.interaction!,encoded=encodeBoundActionV2({version:2,interactionId:active.id,taskId:task,revision:state.revision,actionId:"answer"});expect(decodeBoundActionV2(encoded)?.interactionId).toBe(active.id);const stale=reduceConversationV2(state,event("INBOUND_BUTTON",{boundAction:{version:2,interactionId:active.id,taskId:task,revision:state.revision-1,actionId:"answer"}}),interpretation(),patch(state.revision));expect(stale.nextAction).toBe("STALE_INTERACTION");expect(stale.nextState).toEqual(state);});
  it("invalidates confirmation after any material patch",()=>{let state=started();state=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation(),patch(state.revision,[{op:"set",path:"draft.party",value:{name:"Alfa",role:"client",source:"ad_hoc"},source:"user_current_message",confidence:1}])).nextState;state=conversationStateV2Schema.parse({...state,interaction:null});state=reduceConversationV2(state,event("CONFIRMATION_REQUESTED"),interpretation(),patch(state.revision)).nextState;state=conversationStateV2Schema.parse({...state,interaction:{...state.interaction!,type:"correction",expectedInput:"correction",allowedActions:[]}});const changed=reduceConversationV2(state,event("INBOUND_TEXT"),interpretation("correct"),patch(state.revision,[{op:"set",path:"draft.deadline",value:"20 dias",source:"user_current_message",confidence:1}])).nextState;expect(changed.confirmation?.status).toBe("invalidated");expect(changed.revision).toBe(state.revision+1);});
  it("preserves completed effect checkpoints and models recovery",()=>{let state=started();state=reduceConversationV2(state,event("EFFECT_SUCCEEDED",{effect:"document",requestId:"req",resultRef:"doc"}),interpretation(),patch(state.revision)).nextState;const regressed=reduceConversationV2(state,event("EFFECT_STARTED",{effect:"document",requestId:"req"}),interpretation(),patch(state.revision)).nextState;expect(regressed.effects.document.status).toBe("completed");const failed=reduceConversationV2(regressed,event("EFFECT_FAILED",{effect:"pdf",requestId:"pdf",error:"PDF_STORAGE_FAILED",recoverable:true}),interpretation(),patch(regressed.revision)).nextState;expect(failed.effects.document.status).toBe("completed");expect(failed.recovery).toMatchObject({stage:"pdf",recoverable:true,nextAllowedActions:["retry_pdf","cancel"]});expect(failed.interaction?.type).toBe("recovery");});
  it("preserves active task through interruption",()=>{const state=started(),begun=reduceConversationV2(state,event("INTERRUPTION_START",{taskType:"administrative_query"}),interpretationV2Schema.parse({...interpretation(),intent:"interrupt",interruptionIntent:"administrative_query"}),patch(state.revision)).nextState;expect(begun.activeTask).toEqual(state.activeTask);const resumed=reduceConversationV2(begun,event("INTERRUPTION_COMPLETE"),interpretation("resume"),patch(begun.revision)).nextState;expect(resumed.activeTask).toEqual(state.activeTask);expect(resumed.interaction).toEqual(state.interaction);});
  it("preserves current draft until an explicit switch confirmation",()=>{const state=started(),pending=reduceConversationV2(state,event("TASK_SWITCH_REQUESTED",{taskType:"purchase_order",reason:"user"}),interpretation("switch_task"),patch(state.revision)).nextState;expect(pending.activeTask.type).toBe("quote");expect(pending.pendingSwitch?.toTask).toBe("purchase_order");const switched=reduceConversationV2(pending,event("TASK_SWITCH_CONFIRMED",{taskId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"}),interpretation(),patch(pending.revision)).nextState;expect(switched.activeTask.type).toBe("purchase_order");expect(switched.draft.items).toEqual([]);});
  it("publishes an explicit transition table and one active interaction",()=>{expect(Object.keys(CONVERSATION_V2_TRANSITIONS).length).toBeGreaterThanOrEqual(7);const state=started();expect(state.interaction?.status).toBe("active");expect(Array.isArray(state.interaction)).toBe(false);});
});
