import {describe,expect,it} from "vitest";
import {createConversationStateV2,type ConversationStateV2} from "@/lib/conversation-v2/schema";
import {ConversationQueueEngineV2,nextCursorState,type CrashPointV2} from "@/lib/conversation-v2/queue-engine";
import {MemoryConversationQueueStoreV2} from "@/lib/conversation-v2/memory-queue-store";

const org="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",baseTime=Date.parse("2026-08-16T12:00:00.000Z");
const state=(key:string)=>createConversationStateV2({organizationId:org,conversationKey:key,now:new Date(baseTime).toISOString()});
const transition=(seen:string[])=>(current:ConversationStateV2,job:{externalMessageId:string;receivedAt:string})=>{seen.push(job.externalMessageId);return nextCursorState(current,job as never,new Date(baseTime+10_000).toISOString());};
function setup(keys=["wa:1"],graceMs=0){let time=baseTime,ownerSequence=0;const store=new MemoryConversationQueueStoreV2(keys.map(state));const engine=new ConversationQueueEngineV2(store,{graceMs,clock:()=>new Date(time),ownerToken:()=>`owner-${time}-${ownerSequence++}`});return{store,engine,setTime:(value:number)=>{time=value;}};}
async function enqueue(engine:ConversationQueueEngineV2,key:string,id:string,receivedAt=baseTime){return engine.enqueue({id:`job-${id}`,organizationId:org,conversationKey:key,externalMessageId:`wamid.${id}`,receivedAt:new Date(receivedAt).toISOString(),createdAt:new Date(receivedAt+1).toISOString(),payload:{text:id}});}

describe("Conversation V2 ordered queue",()=>{
  it("deduplicates WAMID and never reprocesses completed jobs",async()=>{const{engine,store}=setup(),seen:string[]=[];expect(await enqueue(engine,"wa:1","dup")).toBe("created");expect(await enqueue(engine,"wa:1","dup")).toBe("duplicate");await engine.drainAvailable(transition(seen));await engine.drainAvailable(transition(seen));expect(seen).toEqual(["wamid.dup"]);expect((await store.getJob("wamid.dup"))?.status).toBe("completed");});
  it("orders one conversation by receivedAt then createdAt/id",async()=>{const{engine,store}=setup(),seen:string[]=[];await enqueue(engine,"wa:1","b",baseTime-100);await enqueue(engine,"wa:1","a",baseTime-200);await enqueue(engine,"wa:1","c",baseTime-100);await engine.drainAvailable(transition(seen));expect(seen).toEqual(["wamid.a","wamid.b","wamid.c"]);expect(store.states.get("wa:1")?.revision).toBe(3);});
  it("serializes ten quick messages in the same conversation",async()=>{const{engine,store}=setup(),seen:string[]=[];for(let i=9;i>=0;i--)await enqueue(engine,"wa:1",String(i),baseTime-100+i);await Promise.all(Array.from({length:5},()=>engine.drainConversation("wa:1",transition(seen))));expect(seen).toEqual(Array.from({length:10},(_,i)=>`wamid.${i}`));expect(store.states.get("wa:1")?.revision).toBe(10);});
  it("allows fifty conversations to progress independently",async()=>{const keys=Array.from({length:50},(_,i)=>`wa:${i}`),{engine,store}=setup(keys);let active=0,maxActive=0;for(let i=0;i<50;i++)await enqueue(engine,keys[i],String(i));await engine.drainAvailable(async(current,job)=>{active++;maxActive=Math.max(maxActive,active);await Promise.resolve();active--;return nextCursorState(current,job,new Date(baseTime+10_000).toISOString());});expect(maxActive).toBeGreaterThan(1);expect([...store.states.values()].every(value=>value.revision===1)).toBe(true);});
  it("uses a bounded grace window to reorder physically inverted arrivals",async()=>{const{engine,setTime}=setup(["wa:1"],500),seen:string[]=[];await enqueue(engine,"wa:1","correction",baseTime+100);setTime(baseTime+200);expect((await engine.drainAvailable(transition(seen))).flatMap(value=>value.processed)).toEqual([]);await enqueue(engine,"wa:1","original",baseTime);setTime(baseTime+700);await engine.drainAvailable(transition(seen));expect(seen).toEqual(["wamid.original","wamid.correction"]);});
});

describe("Conversation V2 lease, recovery and CAS",()=>{
  it("prevents simultaneous owners and permits takeover only after expiry",async()=>{const{store}=setup();expect(await store.acquireLease("wa:1","a",new Date(baseTime).toISOString(),60_000)).toBe(true);expect(await store.acquireLease("wa:1","b",new Date(baseTime+59_999).toISOString(),60_000)).toBe(false);expect(await store.acquireLease("wa:1","b",new Date(baseTime+60_001).toISOString(),60_000)).toBe(true);});
  it("renews only the current unexpired owner lease",async()=>{const{store}=setup();await store.acquireLease("wa:1","a",new Date(baseTime).toISOString(),60_000);expect(await store.renewLease("wa:1","a",new Date(baseTime+30_000).toISOString(),60_000)).toBe(true);expect(await store.renewLease("wa:1","b",new Date(baseTime+31_000).toISOString(),60_000)).toBe(false);expect(store.leases.get("wa:1")?.expiresAt).toBe(new Date(baseTime+90_000).toISOString());});
  it("CAS permits one writer and rejects a stale revision",async()=>{const{store}=setup();await enqueue(new ConversationQueueEngineV2(store,{graceMs:0,clock:()=>new Date(baseTime)}),"wa:1","race");await store.acquireLease("wa:1","owner",new Date(baseTime).toISOString(),60_000);const job=await store.claimNext("wa:1","owner",new Date(baseTime).toISOString());const before=await store.loadState("wa:1"),after=nextCursorState(before,job!,new Date(baseTime+1).toISOString());expect(await store.commitTransition({conversationKey:"wa:1",ownerToken:"owner",jobId:job!.id,expectedRevision:0,nextState:after,now:new Date(baseTime+1).toISOString()})).toBe("committed");expect(await store.commitTransition({conversationKey:"wa:1",ownerToken:"owner",jobId:job!.id,expectedRevision:0,nextState:after,now:new Date(baseTime+2).toISOString()})).toBe("already_completed");expect(store.states.get("wa:1")?.revision).toBe(1);});
  it("prevents lost updates when two jobs calculate from the same revision",async()=>{const{store,engine}=setup();await enqueue(engine,"wa:1","worker-a");await enqueue(engine,"wa:1","worker-b");await store.acquireLease("wa:1","owner",new Date(baseTime).toISOString(),60_000);const jobA=await store.claimNext("wa:1","owner",new Date(baseTime).toISOString()),jobB=await store.claimNext("wa:1","owner",new Date(baseTime).toISOString()),revisionZero=await store.loadState("wa:1"),stateA=nextCursorState(revisionZero,jobA!,new Date(baseTime+1).toISOString()),staleStateB=nextCursorState(revisionZero,jobB!,new Date(baseTime+1).toISOString());expect(await store.commitTransition({conversationKey:"wa:1",ownerToken:"owner",jobId:jobA!.id,expectedRevision:0,nextState:stateA,now:new Date(baseTime+1).toISOString()})).toBe("committed");expect(await store.commitTransition({conversationKey:"wa:1",ownerToken:"owner",jobId:jobB!.id,expectedRevision:0,nextState:staleStateB,now:new Date(baseTime+2).toISOString()})).toBe("cas_conflict");const reloaded=await store.loadState("wa:1"),stateB=nextCursorState(reloaded,jobB!,new Date(baseTime+2).toISOString());expect(await store.commitTransition({conversationKey:"wa:1",ownerToken:"owner",jobId:jobB!.id,expectedRevision:1,nextState:stateB,now:new Date(baseTime+2).toISOString()})).toBe("committed");expect(store.states.get("wa:1")?.revision).toBe(2);});
  it("reloads and retries after a CAS conflict",async()=>{const{store,engine}=setup(),seen:string[]=[];await enqueue(engine,"wa:1","retry");const commit=store.commitTransition.bind(store);let calls=0;store.commitTransition=async input=>++calls===1?"cas_conflict":commit(input);await engine.drainAvailable(transition(seen));expect(calls).toBe(2);expect(seen).toEqual(["wamid.retry","wamid.retry"]);expect(store.states.get("wa:1")?.revision).toBe(1);});
  it("bounds permanent CAS conflicts and makes the job recoverable",async()=>{const{store,engine}=setup();await enqueue(engine,"wa:1","conflict");const commit=store.commitTransition.bind(store);store.commitTransition=async()=>"cas_conflict";await engine.drainAvailable(transition([]));expect((await store.getJob("wamid.conflict"))?.status).toBe("deferred");store.commitTransition=commit;const recovered=new ConversationQueueEngineV2(store,{graceMs:0,clock:()=>new Date(baseTime+251),ownerToken:()=>"recovery"});await recovered.drainAvailable(transition([]));expect((await store.getJob("wamid.conflict"))?.status).toBe("completed");});
  it("recovers stale processing and preserves deferred work across restart",async()=>{const{store,engine,setTime}=setup(),seen:string[]=[];await enqueue(engine,"wa:1","restart");await expect(engine.drainConversation("wa:1",transition(seen),"after_claim")).rejects.toThrow("SIMULATED_CRASH");setTime(baseTime+60_001);const restarted=new ConversationQueueEngineV2(store,{graceMs:0,clock:()=>new Date(baseTime+60_001),ownerToken:()=>"restarted"});expect(await restarted.recover()).toBe(1);await restarted.drainAvailable(transition(seen));expect(seen).toEqual(["wamid.restart"]);expect((await store.getJob("wamid.restart"))?.status).toBe("completed");});
  it.each(["after_claim","after_load","after_reduce","after_persist","after_complete"] as CrashPointV2[])("is idempotent across crash point %s",async(crashPoint)=>{const{store,engine,setTime}=setup(),seen:string[]=[];await enqueue(engine,"wa:1",crashPoint);await expect(engine.drainConversation("wa:1",transition(seen),crashPoint)).rejects.toThrow("SIMULATED_CRASH");setTime(baseTime+60_001);const restarted=new ConversationQueueEngineV2(store,{graceMs:0,clock:()=>new Date(baseTime+60_001),ownerToken:()=>"restart"});await restarted.recover();await restarted.drainAvailable(transition(seen));expect(store.states.get("wa:1")?.revision).toBe(1);expect((await store.getJob(`wamid.${crashPoint}`))?.status).toBe("completed");});
});
