import {describe,expect,it} from "vitest";
import {behaviorCorpusV2,corpusMetricsV2} from "@/lib/conversation-v2/corpus";
import {emptyAgentDraft} from "@/lib/ai/contracts";
import {runConversationV2Shadow} from "@/lib/conversation-v2/shadow";

describe("V2 behavior freeze and shadow",()=>{
  it("versions all mandatory transcripts with complete expectations",()=>{expect(behaviorCorpusV2).toHaveLength(15);for(const transcript of behaviorCorpusV2){expect(transcript.initialContext).toBeTruthy();expect(transcript.inbound).toBeTruthy();expect(transcript.expectedInterpretation).toBeTruthy();expect(transcript.expectedStateTransition).toBeTruthy();expect(transcript.expectedNextAction).toBeTruthy();expect(transcript.expectedEffect).toBeTruthy();expect(transcript.expectedReply).toBeTruthy();}expect(corpusMetricsV2.realTranscripts).toBeGreaterThanOrEqual(12);expect(corpusMetricsV2.knownBadLegacyBehaviors).toBeGreaterThanOrEqual(4);});
  it("keeps explicit divergence classifications",()=>{const values=new Set(behaviorCorpusV2.map(item=>item.comparison));expect(values).toEqual(new Set(["V2_CORRECT_LEGACY_WRONG","BOTH_CORRECT","AMBIGUOUS"]));});
  it("runs shadow without effects or production writes",()=>{const audit=runConversationV2Shadow({organizationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",conversationKey:"wa:1",legacyState:"menu",legacyContext:{draft:emptyAgentDraft(),collection:{}},inbound:{text:"Preciso fazer um orçamento",externalMessageId:"wamid.shadow",receivedAt:"2026-08-16T12:00:00.000Z"},legacyResult:{state:"collecting",draft:{type:"quote"},collection:{activeTask:{type:"quote",nextAction:"ask_counterparty"}}}});expect(audit.sideEffects).toBe(false);expect(audit.v2.intent).toBe("quote");expect(audit.v2.nextAction).toBe("ASK_COUNTERPARTY");});
  it("executes every frozen transcript through isolated shadow",()=>{const results=behaviorCorpusV2.map((transcript,index)=>runConversationV2Shadow({organizationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",conversationKey:`wa:${index}`,legacyState:"menu",legacyContext:{draft:emptyAgentDraft(),collection:{}},inbound:{text:transcript.inbound,externalMessageId:`wamid.corpus.${index}`,receivedAt:`2026-08-16T12:${String(index).padStart(2,"0")}:00.000Z`},legacyResult:{state:"menu",draft:{type:null},collection:{}}}));expect(results).toHaveLength(15);expect(results.every(result=>result.sideEffects===false)).toBe(true);});
});
