import { describe,expect,it } from "vitest";
import { mapLegacyContext } from "@/lib/agent-v1/legacy-mapper";
import { runLumeAgentV1 } from "@/lib/agent-v1/engine";
import { emptyAgentDraft } from "@/lib/ai/contracts";

const turn=(message:string,task?:ReturnType<typeof runLumeAgentV1>["task"])=>runLumeAgentV1({message,task,today:"2026-08-12",now:new Date("2026-08-12T12:00:00Z")});
describe("transcripts completos do Lume Agent V1",()=>{
 it("A — orçamento completo em uma mensagem pergunta somente validade",()=>{const result=turn("Faça um orçamento para a empresa Alfa de 20 lâmpadas a R$ 30 cada, prazo de 20 dias e cartão de crédito em 2 vezes.");expect(result.task).toMatchObject({type:"quote",collectedData:{itemType:"product",items:[{description:"Lâmpadas",quantity:20,unitPrice:30}],deadline:"20 dias",paymentDetails:{method:"credit_card",installments:2},totalPrice:600}});expect(result.task.missingData).toEqual(["validade"]);expect(result.task.currentQuestion?.type).toBe("quote_validity");expect(result.reply).toContain("total fica em R$ 600,00");});
 it("B/C/D — coleta em mensagens e aplica correções sem sobrescrever outros campos",()=>{let result=turn("Quero fazer um orçamento");result=turn("para a empresa Alfa",result.task);result=turn("20 lâmpadas a R$ 30 cada",result.task);result=turn("prazo de 20 dias",result.task);result=turn("cartão em 2 vezes",result.task);expect(result.task.collectedData.items[0]).toMatchObject({description:"Lâmpadas",quantity:20,unitPrice:30});expect(result.task.collectedData.paymentDetails).toMatchObject({installments:2});});
 it("I — pedido de compra completo preserva semântica de fornecedor",()=>{const result=turn("Preciso comprar 20 cadeiras da empresa Alfa a R$ 250 cada, entrega em 15 dias e pagamento via PIX.");expect(result.task.type).toBe("purchase_order");expect(result.task.collectedData).toMatchObject({items:[{description:"Cadeiras",quantity:20,unitPrice:250}],deadline:"15 dias",paymentDetails:{method:"pix"},totalPrice:5000});});
 it("M — nova solicitação supera tarefa antiga contaminada",()=>{const legacy=mapLegacyContext({state:"awaiting_confirmation",context:{draft:{...emptyAgentDraft(),type:"quote",counterpartyName:"Alfa",items:[{description:"vezes",quantity:20,unit:"un",unitPrice:30,discount:0}],paymentTerms:"cartao",deadline:"20 dias",validity:"2026-09-13"},collection:{expectedAnswer:"correction"}}});const result=turn("Faça um orçamento para a empresa Beta de 10 cadeiras a R$ 50 cada, prazo de 5 dias e PIX.",legacy.task);expect(result.task.collectedData.items[0]).toMatchObject({description:"Cadeiras",quantity:10,unitPrice:50});expect(result.task.collectedData.items[0].description).not.toBe("vezes");});
  it("N — menu é resposta e não apaga tarefa",()=>{const active=turn("Faça um orçamento para Alfa de 20 lâmpadas a R$30 cada");const menu=turn("O que você faz?",active.task);expect(menu.task.id).toBe(active.task.id);expect(menu.task.collectedData).toEqual(active.task.collectedData);expect(menu.reply).toContain("Pode me dizer naturalmente");});
  it("J/K — consulta e Cofre interrompem sem destruir a tarefa",()=>{const active=turn("Faça um orçamento para Alfa de 20 lâmpadas a R$30 cada");const tax=turn("Antes, me lembra qual é o CNPJ da minha empresa?",active.task);expect(tax.decision).toMatchObject({intent:"answer_query",taskAction:"interrupt",requestedTool:"find_organization_tax_id"});expect(tax.task.collectedData).toEqual(active.task.collectedData);const vault=turn("Localize o contrato da Alfa",active.task);expect(vault.decision).toMatchObject({taskAction:"interrupt",requestedTool:"search_vault"});expect(vault.task.id).toBe(active.task.id);});
 it("T — texto natural confirma pela mesma questão canônica",()=>{const complete=turn("Faça um orçamento para a empresa Alfa de 20 lâmpadas a R$30 cada, prazo de 20 dias, cartão em duas vezes.");const withValidity=turn("30 dias",complete.task);const confirmTask={...withValidity.task,currentQuestion:{type:"confirm_document",promptId:"confirm",taskId:withValidity.task.id,revision:withValidity.task.revision,allowedActions:["confirm_document","correct_document","cancel_document"],askedAt:new Date().toISOString()}};const confirmed=turn("pode emitir",confirmTask);expect(confirmed.decision).toMatchObject({intent:"confirm_task",taskAction:"confirm",requestedTool:"create_quote"});});
});
