import {beforeEach,describe,expect,it,vi} from "vitest";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({activeBranding:vi.fn(),persistBranding:vi.fn(),findContact:vi.fn()}));
vi.mock("@/lib/branding/store",()=>({activeBranding:mocks.activeBranding,persistBranding:mocks.persistBranding}));
vi.mock("@/lib/ai/tools",()=>({findContact:mocks.findContact,createAgentDraft:vi.fn(),confirmAgentDocument:vi.fn(),queryDocuments:vi.fn()}));
import {emptyAgentDraft} from "@/lib/ai/contracts";
import {runAgentTurn} from "@/lib/ai/turn";
import {buildAgentReviewSummary} from "@/lib/ai/summary";
import {extractEntities,applyEntitiesToAgentDraft} from "@/lib/orchestrator/entities";
import {normalizePaymentTerms,parsePaymentTerms} from "@/lib/domain/payment-terms";
import {CONVERSATION_PROMPT_VERSION,consumeConversationPrompt,createConversationPrompt,resolveActivePrompt} from "@/lib/navigation/conversation-prompts";
import {lumeMessages} from "@/lib/whatsapp/lume-messages";

const ctx={organizationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",userId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",supabase:{} as never};
describe("homologação real — extração e linguagem",()=>{
  it("interpreta 50 lâmpadas a R$ 0,99 cada sem multiplicar ou arredondar incorretamente",()=>{const phrase="Faça um orçamento de 50 lâmpadas para o cliente Matheus Yan no valor de 0,99 centavos cada unidade, pagamento à vista.";const entities=extractEntities(phrase);const draft=applyEntitiesToAgentDraft(emptyAgentDraft(),entities,"quote");expect(entities.value_scope?.value).toBe("unit");expect(draft).toMatchObject({type:"quote",counterpartyName:"Matheus Yan",paymentTerms:"À vista",amountScope:"unit",quotedQuantity:50,quotedAmount:0.99,totalPrice:49.5,items:[{quantity:50,unitPrice:0.99}]});});
  it("preserva o pedido de 20 cadeiras e exige o escopo do preço",()=>{const phrase="Crie um pedido de compra para a empresa alfa de 20 cadeiras por 250 reais pagamento à vista";const entities=extractEntities(phrase);const draft=applyEntitiesToAgentDraft(emptyAgentDraft(),entities,"purchase_order");expect(draft).toMatchObject({type:"purchase_order",counterpartyName:"Empresa alfa",paymentTerms:"À vista",items:[],quotedItemDescription:"Cadeiras",quotedQuantity:20,quotedAmount:250,amountScope:"amount_scope_pending"});expect(entities.value_scope?.value).toBe("amount_scope_pending");expect(String(entities.service?.value)).not.toMatch(/pedido/i);});
  it.each([
    ["Crie pedido para a empresa Alfa de 20 cadeiras a 250 cada","unit"],
    ["Crie pedido para a empresa Alfa de 20 cadeiras por R$ 250 cada","unit"],
    ["Crie pedido para a empresa Alfa de 20 cadeiras, valor unitário de 250 reais","unit"],
    ["Crie pedido para a empresa Alfa de 20 cadeiras, total de R$ 250","total"],
    ["Crie pedido para a empresa Alfa de 20 cadeiras, pedido inteiro por R$ 250","total"],
  ] as const)("resolve o escopo explícito em %s",(text,scope)=>expect(extractEntities(text).value_scope?.value).toBe(scope));
  it("calcula unitário e total somente após a resposta contextual",async()=>{const entities=extractEntities("Crie um pedido de compra para a empresa Alfa de 20 cadeiras por 250 reais pagamento à vista");const pending=applyEntitiesToAgentDraft(emptyAgentDraft(),entities,"purchase_order");const collection={commercialInterpretation:{entities,pendingValueScope:true}};const unit=await runAgentTurn(ctx,{action:"message",text:"1",idempotencyKey:"unit",state:"collecting",draft:pending,collection});expect(unit.draft).toMatchObject({amountScope:"unit",totalPrice:5000,items:[{description:"Cadeiras",quantity:20,unitPrice:250}]});const total=await runAgentTurn(ctx,{action:"message",text:"2",idempotencyKey:"total",state:"collecting",draft:pending,collection});expect(total.draft).toMatchObject({amountScope:"total",totalPrice:250,items:[{description:"Cadeiras",quantity:20,unitPrice:12.5}]});});
  it.each(["A vista","À vista","avista","pagamento a vista","pagamento à vista","em dinheiro à vista","pix à vista","pagamento imediato","pagamento no ato"])("normaliza %s",value=>{expect(normalizePaymentTerms(value)).toBe("À vista");expect(parsePaymentTerms(value)).toBe("À vista");});
  it.each(["A vista","À vista","avista","pagamento a vista"])("%s atualiza o rascunho e não repete a pergunta",async value=>{const draft={...emptyAgentDraft(),type:"purchase_order" as const,counterpartyName:"Empresa Alfa",items:[{description:"cadeiras",quantity:20,unit:"un",unitPrice:30,discount:0}],deadline:"20 dias",paymentTerms:null,deliveryAddress:null};const result=await runAgentTurn(ctx,{action:"message",text:value,idempotencyKey:value,state:"collecting",draft,collection:{party:{source:"registered",name:"Empresa Alfa"}}});expect(result.draft.paymentTerms).toBe("À vista");expect(result.reply).toBe(lumeMessages.address);expect(result.reply).not.toBe(lumeMessages.payment);});
  it("usa linguagem de entrega e avança após prazo",async()=>{const draft={...emptyAgentDraft(),type:"purchase_order" as const,counterpartyName:"Empresa Alfa",items:[{description:"cadeiras",quantity:20,unit:"un",unitPrice:30,discount:0}],deadline:null,paymentTerms:null,deliveryAddress:null};expect(lumeMessages.purchaseOrderDeadline).toBe("Qual é o prazo previsto para entrega?");const result=await runAgentTurn(ctx,{action:"message",text:"20 dias",idempotencyKey:"one",state:"collecting",draft,collection:{party:{source:"registered",name:"Empresa Alfa"}}});expect(result.draft.deadline).toBe("20 dias");expect(result.reply).toBe(lumeMessages.payment);});
  it("separa telefone do endereço e preserva o CEP",async()=>{const draft={...emptyAgentDraft(),type:"purchase_order" as const,counterpartyName:"Empresa Alfa",items:[{description:"cadeiras",quantity:20,unit:"un",unitPrice:250,discount:0}],quotedAmount:250,amountScope:"unit" as const,quotedQuantity:20,quotedItemDescription:"cadeiras",totalPrice:5000,deadline:"2 dias",paymentTerms:"À vista",deliveryAddress:null};mocks.findContact.mockResolvedValue([{id:"contact",legal_name:"Empresa Alfa",tax_id:null}]);const result=await runAgentTurn(ctx,{action:"message",text:"QSC 19, apartamento 306, Taguatinga Centro, Brasília, CEP 71991-000; telefone: (61) 99999-0000",idempotencyKey:"address",state:"collecting",draft,collection:{party:{source:"registered",name:"Empresa Alfa"}}});expect(result.draft.deliveryAddress).toBe("QSC 19, apartamento 306, Taguatinga Centro, Brasília, CEP 71991-000");expect(result.draft.deliveryAddress).not.toMatch(/99999/);expect(result.reply).toContain("Revise os dados do pedido de compra");});
  it("não confirma rascunho legado sem escopo e preserva os demais dados",async()=>{const draft={...emptyAgentDraft(),type:"purchase_order" as const,counterpartyName:"Empresa Alfa",items:[{description:"20 cadeiras",quantity:20,unit:"un",unitPrice:250,discount:0}],deadline:"2 dias",paymentTerms:"À vista",deliveryAddress:"Endereço preservado"};const legacySummary={...buildAgentReviewSummary(draft),version:"commercial-summary-v1"};const result=await runAgentTurn(ctx,{action:"confirm",text:"Confirmar",idempotencyKey:"legacy",state:"awaiting_confirmation",draft,collection:{summary:legacySummary,party:{source:"ad_hoc",name:"Empresa Alfa",taxIdOmitted:true}}});expect(result.state).toBe("collecting");expect(result.reply).toContain("Antes de criar o pedido");expect(result.reply).toContain("1 — Valor de cada cadeira");expect(result.draft).toMatchObject({counterpartyName:"Empresa Alfa",deadline:"2 dias",paymentTerms:"À vista",deliveryAddress:"Endereço preservado",amountScope:"amount_scope_pending",items:[]});});
});

describe("homologação real — personalização e prompts",()=>{
  beforeEach(()=>{vi.clearAllMocks();mocks.persistBranding.mockResolvedValue({id:"x"});});
  const branding={state:"offer" as const,resumeAction:"create_purchase_order" as const};
  it.each([["use_default_document_style","default"],["configure_documents_later","skipped_for_now"]] as const)("%s persiste escolha e retoma pedido",async(action,status)=>{const result=await runAgentTurn(ctx,{action,text:action,idempotencyKey:action,state:"menu",draft:emptyAgentDraft(),collection:{branding}});expect(mocks.persistBranding).toHaveBeenCalledWith(ctx,expect.objectContaining({status}));expect(result.draft.type).toBe("purchase_order");expect(result.reply).toContain(lumeMessages.supplier);expect(result.collection.branding).toBeUndefined();});
  it("cancelar logo usa padrão e retoma sem fallback",async()=>{const result=await runAgentTurn(ctx,{action:"cancel_branding_setup",text:"Cancelar configuração",idempotencyKey:"cancel",state:"menu",draft:emptyAgentDraft(),collection:{branding:{state:"awaiting_logo",resumeAction:"create_quote"}}});expect(mocks.persistBranding).toHaveBeenCalledWith(ctx,{status:"default"});expect(result.draft.type).toBe("quote");expect(result.reply).toBe(lumeMessages.customer);expect(result.reply).not.toContain("essa informação");});
  it("invalida versões antigas e nunca reutiliza prompt consumido",()=>{const current=createConversationPrompt({promptType:"menu",flowId:"main",expectedState:"menu",options:[{number:2,id:"talk_to_lume",label:"Falar com a Lume"}]});expect(CONVERSATION_PROMPT_VERSION).toBe("2026-08-commercial-baseline-v3");expect(resolveActivePrompt("2",{...current,version:"2026-08-homologation-v2"},"menu")).toBeUndefined();expect(resolveActivePrompt("2",consumeConversationPrompt(current),"menu")).toBeUndefined();expect(resolveActivePrompt("2",current,"menu")?.id).toBe("talk_to_lume");});
});
