export type ConversationPromptType = "greeting" | "menu" | "confirmation" | "branding_offer" | "branding_logo" | "branding_template" | "branding_approval" | "continuation";
export type ConversationPromptOption = { number: number; id: string; label: string };
export type ActiveConversationPrompt = { promptId: string; promptType: ConversationPromptType; options: ConversationPromptOption[]; presentedAt: string; flowId: string; version: string; expectedState?: string; menuId?: string; actionId?: string; expiresAt?: string; consumedAt?: string };
export const CONVERSATION_PROMPT_VERSION = "2026-08-commercial-baseline-v3";
export const CONVERSATION_PROMPT_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR").replace(/[^a-z0-9\s_]/g, " ").replace(/\s+/g, " ").trim();
export function createConversationPrompt(input: Omit<ActiveConversationPrompt, "promptId" | "presentedAt" | "version"> & { promptId?: string; presentedAt?: string }) { const presentedAt=input.presentedAt??new Date().toISOString(); return {...input,promptId:input.promptId??`${input.flowId}:${input.promptType}:${presentedAt}`,presentedAt,version:CONVERSATION_PROMPT_VERSION}; }
export function isPromptEligible(prompt?:ActiveConversationPrompt,state?:string,now=new Date()){const presentedAt=prompt?Date.parse(prompt.presentedAt):NaN;return Boolean(prompt&&prompt.version===CONVERSATION_PROMPT_VERSION&&!prompt.consumedAt&&Number.isFinite(presentedAt)&&now.getTime()-presentedAt<=CONVERSATION_PROMPT_MAX_AGE_MS&&(!prompt.expectedState||prompt.expectedState===state)&&(!prompt.expiresAt||Date.parse(prompt.expiresAt)>now.getTime()));}
const contextualAliases:Record<string,string[]>={confirm_document:["sim","pode emitir","pode gerar","pode fazer","esta correto","esta tudo certo","confirmado","manda o pdf","emitir orcamento","emitir pedido"],correct_document:["corrigir informacoes","preciso corrigir","quero corrigir"],cancel_document:["cancelar","nao emitir"],include_cnpj:["sim","incluir cnpj","quero incluir"],skip_cnpj:["nao","nao precisa","sem cnpj"],price_unit:["valor de cada unidade","valor unitario","cada","r 250 cada"],price_total:["valor total","no total","r 250 no total"],personalize_now:["gostaria sim","quero","vamos personalizar","sim","pode colocar minha logo","quero colocar minha logo"],not_now:["agora nao","nao agora","depois","usar nos proximos"],start_intent_switch:["sim","sim comeca","sim comeca o pedido","comeca o pedido","pode comecar","pode trocar"],continue_current_task:["continua","continuar","continua o orcamento","manter tarefa","nao trocar"],cancel_intent_switch:["cancela a troca","deixa pra la","nao quero trocar"]};
export function resolveActivePrompt(raw:string,prompt?:ActiveConversationPrompt,state?:string){if(!isPromptEligible(prompt,state))return undefined;const value=normalize(raw),numeric=/^\d+$/.test(value)?prompt!.options.find(option=>option.number===Number(value)):undefined,direct=prompt!.options.find(option=>normalize(option.id)===value||normalize(option.label)===value),alias=prompt!.options.find(option=>(contextualAliases[option.id]??[]).some(candidate=>normalize(candidate)===value));return numeric??direct??alias;}
export function consumeConversationPrompt(prompt:ActiveConversationPrompt,consumedAt=new Date().toISOString()){return{...prompt,consumedAt};}
export function validateConversationPrompts(prompts:ActiveConversationPrompt[]){const errors:string[]=[],active=prompts.filter(prompt=>isPromptEligible(prompt));if(active.length>1)errors.push("multiple_active_prompts");for(const prompt of active){if(!prompt.options.length)errors.push(`${prompt.promptId}:missing_options`);const numbers=new Set<number>(),ids=new Set<string>();for(const option of prompt.options){if(!option.id||!option.label)errors.push(`${prompt.promptId}:option_without_destination`);if(numbers.has(option.number))errors.push(`${prompt.promptId}:duplicate_number:${option.number}`);if(ids.has(option.id))errors.push(`${prompt.promptId}:duplicate_id:${option.id}`);numbers.add(option.number);ids.add(option.id);}}return{valid:errors.length===0,errors};}
