import "server-only";
import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { administrativeVaultLimits } from "./config";

export const ADMINISTRATIVE_VAULT_BUCKET = "administrative-vault";
const allowed: Record<string,string> = {
  "application/pdf":"pdf","image/jpeg":"jpg","image/png":"png","image/webp":"webp",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":"docx",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"xlsx","text/plain":"txt",
};
export function sanitizeAdministrativeFilename(value:string){const normalized=value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._ -]/g,"").replace(/\.\.+/g,".").replace(/\s+/g,"-").replace(/^-+|-+$/g,"").slice(0,180);return normalized||"arquivo";}
export function classifyAdministrativeFile(input:{filename:string;caption?:string;mimeType:string}){const text=`${input.filename} ${input.caption??""}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(/cartao.*cnpj|comprovante.*inscricao|cadastro.*empresa/.test(text))return"cartão CNPJ";if(/contrato/.test(text))return"contrato";if(/comprovante/.test(text))return"comprovante";if(/proposta/.test(text))return"proposta";if(/orcamento/.test(text))return"orçamento";if(/pedido/.test(text))return"pedido";if(/nota.*fiscal|\bnf-?e\b/.test(text))return"nota fiscal";if(/boleto/.test(text))return"boleto";if(/planilha/.test(text)||input.mimeType.includes("spreadsheet"))return"planilha";if(input.mimeType.startsWith("image/"))return"imagem";return"outro";}
function assertMagic(bytes:Uint8Array,mimeType:string){if(!bytes.length)throw new Error("ADMIN_FILE_EMPTY");if(mimeType==="application/pdf"&&new TextDecoder().decode(bytes.slice(0,5))!=="%PDF-")throw new Error("ADMIN_FILE_CORRUPT");if(mimeType==="image/png"&&!(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47))throw new Error("ADMIN_FILE_CORRUPT");if(mimeType==="image/jpeg"&&!(bytes[0]===0xff&&bytes[1]===0xd8))throw new Error("ADMIN_FILE_CORRUPT");}
export async function storeAdministrativeFile(admin:SupabaseClient,input:{organizationId:string;conversationId?:string;inboundMessageId?:string;userId?:string;providerMediaId?:string;filename:string;mimeType:string;caption?:string;bytes:Uint8Array;occurredAt?:string}){
  const extension=allowed[input.mimeType];if(!extension)throw new Error("ADMIN_FILE_TYPE_INVALID");const limits=administrativeVaultLimits();if(!input.bytes.length)throw new Error("ADMIN_FILE_EMPTY");if(input.bytes.length>limits.maxFileBytes)throw new Error("ADMIN_FILE_TOO_LARGE");assertMagic(input.bytes,input.mimeType);
  const usage=await admin.from("administrative_files").select("size_bytes").eq("organization_id",input.organizationId).is("deleted_at",null);if(usage.error)throw new Error("ADMIN_FILE_USAGE_FAILED");const used=(usage.data??[]).reduce((sum,row)=>sum+Number(row.size_bytes||0),0);if(used+input.bytes.length>limits.organizationBytes)throw new Error("ADMIN_STORAGE_LIMIT_REACHED");
  const sha256=createHash("sha256").update(input.bytes).digest("hex");const duplicate=await admin.from("administrative_files").select("id,document_category,title,storage_path").eq("organization_id",input.organizationId).eq("sha256",sha256).is("deleted_at",null).maybeSingle();if(duplicate.data)return{...duplicate.data,duplicate:true};
  const normalized=sanitizeAdministrativeFilename(input.filename);const category=classifyAdministrativeFile({filename:normalized,caption:input.caption,mimeType:input.mimeType});const path=`${input.organizationId}/${new Date().getUTCFullYear()}/${sha256.slice(0,2)}/${sha256}.${extension}`;
  const upload=await admin.storage.from(ADMINISTRATIVE_VAULT_BUCKET).upload(path,input.bytes,{contentType:input.mimeType,upsert:false});if(upload.error)throw new Error("ADMIN_FILE_STORAGE_FAILED");
  const inserted=await admin.from("administrative_files").insert({organization_id:input.organizationId,conversation_id:input.conversationId??null,inbound_message_id:input.inboundMessageId??null,uploaded_by_user_id:input.userId??null,provider_media_id:input.providerMediaId??null,storage_path:path,original_filename:input.filename.slice(0,255),normalized_filename:normalized,mime_type:input.mimeType,extension,size_bytes:input.bytes.length,sha256,document_category:category,title:input.caption?.slice(0,240)||normalized,extraction_status:["text/plain"].includes(input.mimeType)?"pending":"stored_not_indexed",indexing_status:"pending",occurred_at:input.occurredAt??new Date().toISOString()}).select("id,document_category,title,storage_path").single();
  if(inserted.error||!inserted.data){await admin.storage.from(ADMINISTRATIVE_VAULT_BUCKET).remove([path]);throw new Error("ADMIN_FILE_RECORD_FAILED");}
  await admin.from("audit_logs").insert({organization_id:input.organizationId,actor_id:input.userId??null,action:"administrative_file.stored",entity_type:"administrative_file",entity_id:inserted.data.id,metadata:{category,mimeType:input.mimeType,sizeBytes:input.bytes.length}});return{...inserted.data,duplicate:false};
}
export async function searchAdministrativeFiles(admin:SupabaseClient,input:{organizationId:string;query:string;limit?:number}){const query=input.query.replace(/[%_,]/g," ").trim();let builder=admin.from("administrative_files").select("id,title,original_filename,document_category,mime_type,storage_path,occurred_at,extracted_text").eq("organization_id",input.organizationId).is("deleted_at",null).order("occurred_at",{ascending:false}).limit(input.limit??5);if(query)builder=builder.or(`title.ilike.%${query}%,normalized_filename.ilike.%${query}%,document_category.ilike.%${query}%,extracted_text.ilike.%${query}%`);const result=await builder;if(result.error)throw new Error("ADMIN_FILE_SEARCH_FAILED");return result.data??[];}
export async function signedAdministrativeFileUrl(admin:SupabaseClient,input:{organizationId:string;fileId:string}){const file=await admin.from("administrative_files").select("storage_path,original_filename,mime_type").eq("id",input.fileId).eq("organization_id",input.organizationId).is("deleted_at",null).single();if(file.error||!file.data)throw new Error("ADMIN_FILE_NOT_FOUND");const signed=await admin.storage.from(ADMINISTRATIVE_VAULT_BUCKET).createSignedUrl(file.data.storage_path,300);if(signed.error||!signed.data?.signedUrl)throw new Error("ADMIN_FILE_SIGN_FAILED");return{url:signed.data.signedUrl,filename:file.data.original_filename,mimeType:file.data.mime_type};}
