import { notFound } from "next/navigation";
import { requireMembership } from "@/lib/auth/session";
import { prepareQuoteConversion } from "@/lib/operations/conversion";
import { createOrderFromQuote } from "../../actions";
export default async function QuoteToOrder({params}:{params:Promise<{id:string}>}) {
  const {id}=await params,{supabase,organizationId,user,role}=await requireMembership();
  let draft; try { draft=await prepareQuoteConversion({supabase,organizationId,userId:user.id,role},id); } catch { notFound(); }
  const {data:members}=await supabase.from("organization_members").select("user_id,profiles(full_name)").eq("organization_id",organizationId);
  return <><div className="topline"><div><span className="eyebrow">REVISÃO OBRIGATÓRIA</span><h1>Criar ordem de serviço</h1><p className="muted">O orçamento permanece inalterado. A numeração só será reservada após esta confirmação.</p></div></div><form className="panel form-grid" action={createOrderFromQuote}><input type="hidden" name="quote_id" value={id}/><label className="field">Título<input name="title" required minLength={3}/></label><label className="field">Local<input name="location" required minLength={3}/></label><label className="field">Responsável<select name="responsible_id" required><option value="">Selecione</option>{(members??[]).map(m=><option key={m.user_id} value={m.user_id}>{(m.profiles as unknown as {full_name:string})?.full_name??"Usuário"}</option>)}</select></label><label className="field">Prioridade<select name="priority"><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="field">Data prevista<input type="datetime-local" name="scheduled_at"/></label><label className="field">Prazo<input type="datetime-local" name="due_at"/></label><section className="full"><h2>Dados copiados</h2><p>{draft.description}</p><p className="help">Cliente, escopo, observações e vínculo de origem serão preservados. Responsável, local, prioridade e datas são informados acima.</p></section><button className="button">Confirmar e criar uma ordem</button></form></>;
}
