import { z } from "zod";
import { extractEntities } from "@/lib/orchestrator/entities";
import { parseItemBundle, parseDeadlineAnswer, paymentOnlyUpdate } from "@/lib/ai/contextual-understanding";
import { parseQuoteValidity } from "@/lib/ai/validity";
import type { TaskStateV1 } from "./task-state";

export const semanticPatchSchema=z.object({operation:z.enum(["set","update","clear"]),field:z.enum(["type","counterpartyName","item","quantity","unitPrice","deadline","payment","validity","deliveryAddress","notes","documentQuery"]),value:z.unknown(),confidence:z.number().min(0).max(1),source:z.enum(["user_current_message","inference"])});
export const lumeAgentDecisionSchema=z.object({agentVersion:z.literal("lume-agent-v1"),intent:z.enum(["start_task","continue_task","correct_task","confirm_task","cancel_task","answer_query","show_capabilities","greeting","unknown"]),taskAction:z.enum(["create","patch","confirm","cancel","interrupt","resume","none"]),taskType:z.enum(["quote","purchase_order","document_search","administrative_query","branding","branding_setup"]).nullable(),patches:z.array(semanticPatchSchema).max(20),ambiguities:z.array(z.string().max(240)).max(10),requestedTool:z.enum(["create_quote","create_purchase_order","find_document","find_organization_tax_id","search_vault","configure_branding"]).nullable(),nextQuestion:z.string().max(80).nullable(),confirmationRequired:z.boolean(),confidence:z.number().min(0).max(1)});
export type LumeAgentDecision=z.infer<typeof lumeAgentDecisionSchema>;
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const patch=(field:z.infer<typeof semanticPatchSchema>["field"],value:unknown,confidence=.98)=>({operation:"set" as const,field,value,confidence,source:"user_current_message" as const});
const title=(value:string)=>value.charAt(0).toLocaleUpperCase("pt-BR")+value.slice(1);
export function decideLumeAgentV1(message:string,task?:TaskStateV1,today?:string):LumeAgentDecision{const n=normalize(message),patches:z.infer<typeof semanticPatchSchema>[]=[],entities=extractEntities(message,{today}),startsQuote=/\b(?:orcamento|proposta)\b/.test(n),startsPurchase=/\b(?:pedido de compra|preciso comprar|comprar)\b/.test(n),taskType=startsPurchase?"purchase_order":startsQuote?"quote":task?.type??null;
 if(/^(?:boa tarde|bom dia|boa noite|oi|ola)(?: lume)?$/.test(n))return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"greeting",taskAction:"none",taskType:task?.type??null,patches:[],ambiguities:[],requestedTool:null,nextQuestion:null,confirmationRequired:false,confidence:1});
 if(/^(?:menu|o que voce faz|quais sao suas funcoes|como voce pode ajudar)$/.test(n))return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"show_capabilities",taskAction:"none",taskType:task?.type??null,patches:[],ambiguities:[],requestedTool:null,nextQuestion:null,confirmationRequired:false,confidence:1});
 if(/\b(?:qual|lembra|informe|mostrar|mostre)\b.*\b(?:meu|minha|empresa)\b.*\bcnpj\b|\bcnpj\b.*\b(?:meu|minha|empresa)\b/.test(n))return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"answer_query",taskAction:task?"interrupt":"none",taskType:task?.type??"administrative_query",patches:[],ambiguities:[],requestedTool:"find_organization_tax_id",nextQuestion:task?"resume_task":null,confirmationRequired:false,confidence:.99});
 if(/\b(?:procure|busque|localize|encontre|envie|mande)\b.*\b(?:arquivo|documento|contrato|comprovante|cartao cnpj)\b/.test(n))return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"answer_query",taskAction:task?"interrupt":"none",taskType:task?.type??"administrative_query",patches:[],ambiguities:[],requestedTool:"search_vault",nextQuestion:task?"resume_task":null,confirmationRequired:false,confidence:.96});
 if(task?.currentQuestion?.type==="confirm_document"&&/^(?:sim|pode emitir|pode gerar|manda|esta correto|esta tudo certo|confirmado)$/.test(n))return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"confirm_task",taskAction:"confirm",taskType:task.type,patches:[],ambiguities:[],requestedTool:task.type==="quote"?"create_quote":task.type==="purchase_order"?"create_purchase_order":null,nextQuestion:null,confirmationRequired:true,confidence:1});
 const bundle=parseItemBundle(message),originalItem=/(?:^|[.\n]\s*|\bde\s+)(?:são\s+)?\d+\s+([\p{L}][\p{L}\s-]*?)(?=\s+(?:a|por)\s+(?:r\$\s*)?\d)/iu.exec(message)?.[1]?.trim(),cleanEntity=String(entities.service?.value??"").replace(/\s+d[ao]\s+empresa\s+[\p{L}0-9 .&-]+$/iu,"").trim(),semantic=normalize(originalItem??cleanEntity??bundle?.description??"");if(bundle)patches.push(patch("item",{...bundle,description:title(originalItem??bundle.description),itemType:/\b(?:lampad|cadeir|notebook|equipamento|produto)/.test(semantic)?"product":/\b(?:instal|manut|consult|servic)/.test(semantic)?"service":bundle.itemType}));else if(entities.service&&entities.quantity&&entities.price)patches.push(patch("item",{description:title(originalItem??cleanEntity),quantity:Number(entities.quantity.value),unitPrice:Number(entities.price.value),itemType:/\b(?:lampad|cadeir|notebook|equipamento|produto)/.test(semantic)?"product":/\b(?:instal|manut|consult|servic)/.test(semantic)?"service":"unknown"}));
 const explicitParty=/(?:\bpara\s+(?:a\s+empresa\s+)?|\bda\s+(?:empresa\s+)?)([\p{L}][\p{L}0-9 .&-]*?)(?=\s+(?:de\s+\d+|por\s+(?:r\$)?\s*\d+|a\s+(?:r\$)?\s*\d+|,|$))/iu.exec(message)?.[1]?.trim()??(task?.currentQuestion?.type==="counterparty"?message.replace(/^\s*(?:para\s+)?(?:a\s+empresa\s+)?/iu,"").replace(/[,.]+$/g,"").trim():undefined);
 if(typeof entities.customer?.value==="string"||explicitParty)patches.push(patch("counterpartyName",explicitParty??entities.customer!.value,.94));
 const deadline=parseDeadlineAnswer(message);if(deadline)patches.push(patch("deadline",deadline));
 const payment=paymentOnlyUpdate(message);if(payment)patches.push(patch("payment",payment.display));
 const validity=task?.currentQuestion?.type==="quote_validity"||/\bvalid(?:ade|o|a)\b/.test(n)?parseQuoteValidity(message,today):undefined;if(validity?.success)patches.push(patch("validity",validity.canonical));
 if(task?.currentQuestion?.type==="payment_terms"&&!payment)return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent:"continue_task",taskAction:"none",taskType:task.type,patches:[],ambiguities:["payment_terms"],requestedTool:null,nextQuestion:"payment_terms",confirmationRequired:false,confidence:.45});
 const intent=startsQuote||startsPurchase?"start_task":patches.length?task?"continue_task":"start_task":"unknown";return lumeAgentDecisionSchema.parse({agentVersion:"lume-agent-v1",intent,taskAction:patches.length?task?"patch":"create":"none",taskType,patches,ambiguities:[],requestedTool:null,nextQuestion:null,confirmationRequired:false,confidence:patches.length?.94:.2});}
