import { createHash } from "node:crypto";
import { agentDraftSchema } from "@/lib/ai/contracts";
import { currentQuestionSchema, taskStateV1Schema, type TaskStateV1 } from "./task-state";

export function presentTaskConfirmation(task:TaskStateV1,now=new Date()){if(task.missingData.length)throw new Error("TASK_CONFIRMATION_MISSING_DATA");const snapshot=agentDraftSchema.parse(task.collectedData),fingerprint=createHash("sha256").update(`${task.id}:${task.revision}:${JSON.stringify(snapshot)}`).digest("hex"),timestamp=now.toISOString(),question=currentQuestionSchema.parse({type:"confirm_document",promptId:`${task.id}:confirm:${task.revision}`,taskId:task.id,revision:task.revision,allowedActions:["confirm_document","correct_document","cancel_document"],askedAt:timestamp});return taskStateV1Schema.parse({...task,status:"awaiting_confirmation",currentQuestion:question,confirmation:{status:"pending",taskId:task.id,revision:task.revision,presentedSnapshot:snapshot,fingerprint,requestedAt:timestamp,confirmedAt:null},toolExecution:{...task.toolExecution,status:"pending_confirmation"},timestamps:{...task.timestamps,updatedAt:timestamp}});}
export function confirmTask(task:TaskStateV1,input:{taskId:string;revision:number;now?:Date}){if(task.id!==input.taskId||task.revision!==input.revision||task.confirmation.taskId!==input.taskId||task.confirmation.revision!==input.revision||task.confirmation.status!=="pending"||!task.confirmation.fingerprint)throw new Error("TASK_CONFIRMATION_STALE");const timestamp=(input.now??new Date()).toISOString(),toolId=task.type==="quote"?"create_quote":task.type==="purchase_order"?"create_purchase_order":null;if(!toolId)throw new Error("TASK_TOOL_UNAVAILABLE");return taskStateV1Schema.parse({...task,status:"executing",currentQuestion:null,confirmation:{...task.confirmation,status:"confirmed",confirmedAt:timestamp},toolExecution:{toolId,status:"executing",requestId:task.toolExecution.requestId??`${task.id}:${task.revision}`,startedAt:task.toolExecution.startedAt??timestamp,completedAt:null,resultRef:null,error:null},timestamps:{...task.timestamps,updatedAt:timestamp}});}
export function completeTaskTool(task:TaskStateV1,resultRef:string,now=new Date()){if(task.toolExecution.status==="completed")return task;if(task.status!=="executing"||task.toolExecution.status!=="executing")throw new Error("TASK_TOOL_NOT_EXECUTING");const timestamp=now.toISOString();return taskStateV1Schema.parse({...task,status:"completed",toolExecution:{...task.toolExecution,status:"completed",completedAt:timestamp,resultRef,error:null},timestamps:{...task.timestamps,updatedAt:timestamp,completedAt:timestamp}});}
export function failTaskTool(task:TaskStateV1,error:string,recoverable=true,now=new Date()){const timestamp=now.toISOString();return taskStateV1Schema.parse({...task,status:recoverable?"awaiting_confirmation":"cancelled",toolExecution:{...task.toolExecution,status:recoverable?"failed_recoverable":"failed_terminal",completedAt:timestamp,error},timestamps:{...task.timestamps,updatedAt:timestamp}});}
export function beginInterruption(task:TaskStateV1,kind:NonNullable<TaskStateV1["interruption"]>["kind"],now=new Date()){return taskStateV1Schema.parse({...task,interruption:{kind,requestedAt:now.toISOString(),resumeQuestion:task.currentQuestion,status:"pending"}});}
export function completeInterruption(task:TaskStateV1){if(!task.interruption)return task;return taskStateV1Schema.parse({...task,currentQuestion:task.interruption.resumeQuestion,interruption:null});}
