import { agentDraftSchema, type AgentDraft } from "@/lib/ai/contracts";
import { calculateDocument } from "@/lib/domain/calculations";
import { isPaymentOnlyDescription, parsePaymentDetails } from "@/lib/domain/payment-terms";
import { refreshTaskState, type TaskStateV1 } from "./task-state";

export type PatchField="type"|"counterpartyName"|"item"|"quantity"|"unitPrice"|"deadline"|"payment"|"validity"|"deliveryAddress"|"notes"|"documentQuery";
export type SemanticPatch={operation:"set"|"update"|"clear";field:PatchField;value:unknown;confidence:number;source:"user_current_message"|"inference"};
export type PatchApplication={task:TaskStateV1;accepted:PatchField[];rejected:Array<{field:PatchField;reason:string}>};
const questionPermissions:Record<string,PatchField[]>={counterparty:["counterpartyName"],item_bundle:["item","quantity","unitPrice"],delivery_deadline:["deadline","payment"],payment_terms:["payment"],quote_validity:["validity"],delivery_address:["deliveryAddress"],confirm_document:[],correction:["counterpartyName","item","quantity","unitPrice","deadline","payment","validity","deliveryAddress","notes"]};
export function applySemanticPatches(task:TaskStateV1,patches:SemanticPatch[],now=new Date()):PatchApplication{let draft:AgentDraft=task.collectedData;const accepted:PatchField[]=[],rejected:PatchApplication["rejected"]=[],allowed=task.currentQuestion?new Set(questionPermissions[task.currentQuestion.type]??[]):null;for(const patch of patches){if(patch.confidence<.7){rejected.push({field:patch.field,reason:"low_confidence"});continue;}if(allowed&&allowed.size&&!allowed.has(patch.field)){rejected.push({field:patch.field,reason:"field_not_authorized_by_current_question"});continue;}try{if(patch.field==="counterpartyName")draft=agentDraftSchema.parse({...draft,counterpartyName:String(patch.value).trim()});else if(patch.field==="item"){const value=patch.value as {description:string;quantity:number;unitPrice:number;itemType?:"product"|"service"|"mixed"|"unknown"};if(isPaymentOnlyDescription(value.description))throw new Error("payment_term_as_item");draft=agentDraftSchema.parse({...draft,items:[{description:value.description,quantity:value.quantity,unit:"un",unitPrice:value.unitPrice,discount:0}],quotedItemDescription:value.description,quotedQuantity:value.quantity,quotedAmount:value.unitPrice,amountScope:"unit",itemType:value.itemType??"unknown"});}else if(patch.field==="quantity"){if(draft.items.length!==1)throw new Error("item_required");draft=agentDraftSchema.parse({...draft,items:[{...draft.items[0],quantity:Number(patch.value)}],quotedQuantity:Number(patch.value)});}else if(patch.field==="unitPrice"){if(draft.items.length!==1)throw new Error("item_required");draft=agentDraftSchema.parse({...draft,items:[{...draft.items[0],unitPrice:Number(patch.value)}],quotedAmount:Number(patch.value),amountScope:"unit"});}else if(patch.field==="payment"){const payment=parsePaymentDetails(String(patch.value));if(!payment)throw new Error("payment_invalid");draft=agentDraftSchema.parse({...draft,paymentTerms:payment.display,paymentDetails:payment});}else draft=agentDraftSchema.parse({...draft,[patch.field]:patch.operation==="clear"?null:patch.value});const totals=draft.items.length?calculateDocument(draft.items,draft.shipping??0):null;draft=agentDraftSchema.parse({...draft,totalPrice:totals?.total??null});accepted.push(patch.field);}catch(error){rejected.push({field:patch.field,reason:error instanceof Error?error.message:"invalid_patch"});}}
 const next=refreshTaskState(task,draft,now),timestamp=now.toISOString(),provenance={...next.provenance};for(const patch of patches.filter(p=>accepted.includes(p.field)))provenance[patch.field]={source:patch.source,confidence:patch.confidence,timestamp,revision:next.revision};return{task:{...next,provenance},accepted,rejected};}
